'use strict';
/* Compare (9.0). Two modes:
   - odds: the main market of every match offered by at least two bookmakers, one column per bookmaker, best price per
     side marked, margins and arbitrage (best prices below 100 %) shown; data comes from the feed quotes (no requests);
   - schedule: the 8.x schedule-file tool (HTM/HTML/Markdown/text) matched against the line by the server. */
let imported=null,importText='',comparison=null,compareFilter='all',compareBusy=false;

function renderCompare(force){if(prefs.compareMode==='schedule')renderScheduleCompare(force);else renderOddsCompare(force);}
// The schedule tool is a form: feed updates must not rebuild it (and lose the text being typed).
const scheduleSignature=()=>JSON.stringify([!!imported,imported?.events?.length,imported?.year,imported?.offsetMinutes,comparison?.revision,comparison?.matches?.length,compareFilter,compareBusy,rules().revision]);

function renderOddsCompare(force){
 const el=viewEl('compare'),scope=prefs.compareScope,s=snapshots[scope],books=viewBooks(scope).filter(bookVisible);
 const all=visible(feedRows(scope),'compare',{ignoreCategory:true});categoryOptions(all,null,'compare');
 const cat=filters('compare').category,rows=(cat?all.filter(e=>norm(e.category)===cat):all).map(e=>({e,quotes:quotesOf(e,books)})).filter(x=>Object.values(x.quotes).filter(q=>q&&!q.s&&MatchFormat.openPrice(q.h)&&MatchFormat.openPrice(q.a)).length>=2);
 const sig=JSON.stringify(['odds',scope,s?.revision,s?.receivedAt,s?.persisted,rows.length,books,filters('compare'),prefs.onlyFavorites,prefs.favorites.length,selectedId('compare')]);
 if(!force&&viewSignatures.get('compare')===sig)return;viewSignatures.set('compare',sig);
 if(prefs.hideOdds){renderState(el,{title:'Коэффициенты скрыты',text:'Включите показ коэффициентов в настройках, чтобы сравнивать цены контор.',actions:'<button class="btn" data-open-settings="display">Открыть настройки</button>'});updateListHead('compare',0);return;}
 if(!rows.length){if(!s)skeleton(el);else renderState(el,all.length?{title:'Нет матчей у нескольких контор',text:`В ${scope==='live'?'LIVE':'линии'} нет матчей с основным рынком хотя бы у двух выбранных контор.`}:emptyFor(scope,s));updateListHead('compare',0);return;}
 rows.sort((a,b)=>scope==='live'?MatchView.clock(b.e,'live')-MatchView.clock(a.e,'live'):Number(a.e.startAt||0)-Number(b.e.startAt||0));
 const head=`<thead><tr><th>Матч</th>${books.map(b=>`<th><span class="book-mark ${b}" aria-hidden="true"></span> ${esc(providerName(b))}</th>`).join('')}<th>Лучшие</th><th title="Маржа конторы: чем меньше, тем выгоднее цены">Маржа</th></tr></thead>`;
 const body=rows.map(({e,quotes})=>{
  const best=bestFor(quotes),sel=selectedId('compare')===String(e.id),margins=books.map(b=>MatchFormat.margin(quotes[b])).filter(v=>v!=null),bestSum=best.h&&best.a?(1/best.h+1/best.a)*100:null,arb=bestSum!=null&&bestSum<100;
  const when=scope==='live'?esc(MatchFormat.scoreParts(e,e).text||'LIVE'):esc(stamp(e.startAt,true));
  const cells=books.map(b=>{const q=quotes[b];if(!q)return '<td class="margin muted">—</td>';if(q.s)return '<td class="margin muted" title="приостановлено">⏸</td>';const p=side=>{const v=MatchFormat.openPrice(q[side]);if(v==null)return '<span class="price none">—</span>';const t=quoteTracker.track(`cmp:${b}:${e.id}:${side}`,v),isBest=v===best[side]&&best.countSide[side]>1;return `<span class="price${isBest?' best':''}"${isBest?` aria-label="${esc(MatchFormat.formatPrice(v))}, лучший"`:''}>${t.dir?`<span class="chg ${t.dir}">${t.dir==='up'?'▲':'▼'}</span>`:''}${esc(MatchFormat.formatPrice(v))}</span>`;};return `<td><div class="p2">${p('h')}${p('a')}</div></td>`;}).join('');
  const bestCell=`<td class="best-col"><div class="p2"><span class="price">${esc(MatchFormat.formatPrice(best.h))} <small class="muted">${esc(best.by.h.map(providerName).join(', '))}</small></span><span class="price">${esc(MatchFormat.formatPrice(best.a))} <small class="muted">${esc(best.by.a.map(providerName).join(', '))}</small></span></div></td>`;
  return `<tr data-id="${esc(e.id)}" tabindex="0" aria-selected="${sel}"><td><div class="teams"><div class="meta">${gameIcon(e.category)}<span>${esc(leagueTitle(e))} · ${when}</span></div><div class="team"><span class="name">${esc(e.team1)}</span></div><div class="team"><span class="name">${esc(e.team2)}</span></div></div></td>${cells}${bestCell}<td class="margin">${margins.length?`${Math.min(...margins).toFixed(1)}%`:'—'}${arb?`<div class="status-text good" title="Сумма обратных лучших цен ${bestSum.toFixed(1)}%">вилка ${(100-bestSum).toFixed(1)}%</div>`:''}</td></tr>`;
 }).join('');
 morphInto(el,`<table class="cmp-table" data-group="table">${head}<tbody>${body}</tbody></table>`);
 updateListHead('compare',rows.length);
}

// ---------------------------------------------------------------------------------------------------- schedule file
function compareVisible(events){const rule=rules(),state={publishedLeagueLinks:rule.links||[],excludedLeagueKeys:[...hiddenKeys('compare'),...(rule.visibility?.excludedLeagueKeys||[])],excludedCategoryKeys:rule.visibility?.excludedCategoryKeys||[]};return (events||[]).filter(e=>e&&!LeagueModel.hidden(e,state));}
function comparisonProviders(e){return refs(e).filter(r=>prefs[r.source]!==false&&BOOKS.includes(r.source)).map(r=>`<span class="chip"><span class="book-mark ${esc(r.source)}" aria-hidden="true"></span>${providerName(r.source)} ${stamp(r.startAt,true)}</span>`).join(' ');}
function comparisonGroups(items){const groups=new Map();for(const item of items){const e=item.event,key=norm(e.category)+'|'+norm(leagueTitle(e));if(!groups.has(key))groups.set(key,{e,rows:[]});groups.get(key).rows.push(item);}return [...groups.values()].sort((a,b)=>alphabet.compare(a.e.category||'',b.e.category||'')||alphabet.compare(leagueTitle(a.e),leagueTitle(b.e))).map(g=>`<div class="group-head" style="position:static">${gameIcon(g.e.category)}<span>${esc(g.e.category||'')}</span><span class="league">${esc(leagueTitle(g.e))}</span><span class="n">${g.rows.length}</span></div>${g.rows.sort((a,b)=>Number(a.event.startAt)-Number(b.event.startAt)).map(r=>r.html).join('')}`).join('');}
async function runComparison(){if(compareBusy||!imported)return;compareBusy=true;renderCompare(true);try{comparison=await client.post('/api/prematch/compare',{events:imported.events,options:{astekEnabled:prefs.astek!==false,fonbetEnabled:prefs.fonbet!==false,pinnacleEnabled:prefs.pinnacle!==false,excludedLeagueKeys:hiddenKeys('compare')}});}catch(error){report(error);}finally{compareBusy=false;if(tab==='compare')renderCompare(true);}}
function renderScheduleCompare(force){
 const el=viewEl('compare'),sig='schedule:'+scheduleSignature();
 if(!force&&viewSignatures.get('compare')===sig&&el.querySelector('#scheduleFile'))return;viewSignatures.set('compare',sig);
 if(comparison&&comparison.revision<rules().revision&&!compareBusy){comparison=null;runComparison();return;}
 const draft=$('scheduleText')?.value,inputRows=compareVisible(imported?.events||[]);
 el.innerHTML=`<div class="cmp-mode"><section class="setting-card"><h3>1. Загрузите расписание</h3><p>HTM / HTML / Markdown, включая CustomLine и Betshop printed. Читаются турниры, даты и команды; коэффициенты пропускаются.</p><div class="row-actions"><input id="scheduleFile" type="file" accept=".htm,.html,.md,.txt,text/html,text/plain,text/markdown"><label class="check">Год <input id="importYear" class="input" type="number" min="2000" max="2100" value="${imported?.year||new Date().getFullYear()}" style="width:90px"></label><label class="check">Время в файле <select id="importZone" class="select"><option value="240">UTC+4</option><option value="180">UTC+3</option><option value="0">UTC</option></select></label></div><details style="margin-top:12px"><summary>Или вставьте расписание текстом</summary><p class="muted">Таблица Betshop printed целиком или строки: 21.09.2026 18:00 | Counter Strike 2 | CCT Europe | Nexus - Bushido Wildcats</p><textarea id="scheduleText" class="input" rows="4" style="width:100%;height:auto;padding:8px" placeholder="Дата время | Игра | Лига | Команда 1 - Команда 2"></textarea><div class="row-actions" style="margin-top:8px"><button id="parseText" class="btn">Прочитать текст</button></div></details></section>
 ${imported?`<section class="setting-card"><h3>2. Распознанные матчи · ${inputRows.length}</h3><p>Время приведено к UTC+4. ${imported.duplicates?`Повторы удалены: ${imported.duplicates}.`:''} ${imported.errors.length?`Не прочитано строк: ${imported.errors.length}.`:''}</p>${imported.errors.length?`<details><summary>Ошибки импорта</summary><pre class="code">${esc(imported.errors.join('\n'))}</pre></details>`:''}<div style="max-height:320px;overflow:auto;border:1px solid var(--line);border-radius:6px">${comparisonGroups(inputRows.map(e=>({event:e,html:`<div class="comparison-row"><strong>${esc(e.team1)} - ${esc(e.team2)}</strong><span>${stamp(e.startAt,true)}</span></div>`})))}</div><div class="row-actions" style="margin-top:12px"><button id="compareRun" class="btn primary" ${compareBusy?'disabled':''}>${compareBusy?'Сравниваем…':'Сравнить с линией'}</button><span class="muted">Учитываются выбранные конторы и скрытые лиги</span></div></section>`:''}<div id="comparisonOutput"></div></div>`;
 $('importZone').value=String(imported?.offsetMinutes??240);if(draft!==undefined)$('scheduleText').value=draft;
 async function read(){try{if(!importText)return;imported={...ScheduleImport.parse(importText,{year:Number($('importYear').value),offsetMinutes:Number($('importZone').value)}),offsetMinutes:Number($('importZone').value)};comparison=null;renderCompare(true);}catch(error){report(error);}}
 $('scheduleFile').onchange=async()=>{const file=$('scheduleFile').files[0];if(!file)return;if(file.size>10*1024*1024){toast('Файл слишком большой: максимум 10 МБ');return;}importText=await file.text();await read();};$('importYear').onchange=read;$('importZone').onchange=read;
 $('parseText').onclick=()=>{if(/Betshop printed|(?:Esports|Киберспорт)\s*[.:]/i.test($('scheduleText').value)){importText=$('scheduleText').value;read();return;}try{const rows=$('scheduleText').value.trim().split('\n').filter(Boolean);const events=rows.map((line,i)=>{const parts=line.split('|').map(s=>s.trim()),date=parts[0].match(/^(\d{2})\.(\d{2})\.(\d{4})\s+(\d{2}):(\d{2})$/),teams=(parts[3]||'').split(/\s+[—–-]\s+/);if(!date||teams.length!==2||!parts[2])throw new Error(`Проверьте формат строки ${i+1}`);return {startAt:Date.UTC(+date[3],+date[2]-1,+date[1],+date[4],+date[5])-Number($('importZone').value)*60000,category:parts[1],league:parts[2],team1:teams[0],team2:teams[1]};});if(!events.length)throw new Error('Вставьте расписание');imported={events,errors:[],duplicates:0,year:Number($('importYear').value),offsetMinutes:Number($('importZone').value)};importText='';comparison=null;renderCompare(true);}catch(error){report(error);}};
 if($('compareRun'))$('compareRun').onclick=runComparison;
 updateListHead('compare',inputRows.length);
 if(!comparison)return;
 const result={...comparison,matches:comparison.matches.filter(m=>compareVisible([m.astek]).length),missingInput:compareVisible(comparison.missingInput),onlyAstek:compareVisible(comparison.onlyAstek)};
 $('comparisonOutput').innerHTML=`<section class="setting-card"><h3>3. Результат сравнения</h3><div class="segmented" role="group" aria-label="Фильтр результата">${[['all','Все'],['matched',`Совпали · ${result.matches.length}`],['time',`Разное время · ${result.matches.filter(m=>m.minutes>=1).length}`],['missing',`Есть в файле · ${result.missingInput.length}`],['extra',`Нет в файле · ${result.onlyAstek.length}`]].map(([value,label])=>`<button type="button" data-compare-filter="${value}" aria-pressed="${compareFilter===value}">${label}</button>`).join('')}</div><p class="muted">Скрыто правилами: ${result.hiddenInputs||0}. «Есть в файле» также может означать неоднозначные названия или уже начавшийся матч.</p><div id="comparisonRows" style="border:1px solid var(--line);border-radius:6px"></div></section>`;
 const rows=[];
 if(['all','matched','time'].includes(compareFilter))for(const m of result.matches){if(compareFilter==='time'&&m.minutes<1)continue;rows.push({event:m.astek,html:`<div class="comparison-row"><div><span class="pill">Файл</span><strong>${esc(m.input.team1)} - ${esc(m.input.team2)}</strong><small>${esc(leagueTitle(m.input))} · ${stamp(m.input.startAt,true)}</small></div><div><span class="${m.minutes>=1?'bad':'good'}">${m.minutes>=1?'Разница '+Math.round(m.minutes)+' мин':'Совпало'} · ${Math.round(m.score*100)}%</span> <strong>${esc(m.astek.team1)} - ${esc(m.astek.team2)}</strong><small>${comparisonProviders(m.astek)}${m.swapped?' · обратный порядок команд':''}</small></div></div>`});}
 if(['all','missing'].includes(compareFilter))for(const e of result.missingInput)rows.push({event:e,html:`<div class="comparison-row"><div><strong>${esc(e.team1)} - ${esc(e.team2)}</strong><small>${esc(leagueTitle(e))} · ${stamp(e.startAt,true)}</small></div><div class="bad">Не найдено уверенного совпадения в линии</div></div>`});
 if(['all','extra'].includes(compareFilter))for(const e of result.onlyAstek)rows.push({event:e,html:`<div class="comparison-row"><div><strong>${esc(e.team1)} - ${esc(e.team2)}</strong><small>${esc(leagueTitle(e))} · ${stamp(e.startAt,true)}</small></div><div class="muted">Есть в линии, нет в файле <span>${comparisonProviders(e)}</span></div></div>`});
 $('comparisonRows').innerHTML=comparisonGroups(rows)||'<div class="state"><strong>Нет расхождений в этой группе</strong></div>';
 $('comparisonOutput').querySelectorAll('[data-compare-filter]').forEach(b=>b.onclick=()=>{compareFilter=b.dataset.compareFilter;renderCompare(true);});
 updateListHead('compare',result.matches.length+result.missingInput.length+result.onlyAstek.length);
}
