const Cs2Panel=(()=>{
 const opened=new Map();let ctx;
 const clockSeconds=value=>{if(value==null||value==='')return null;if(typeof value==='number'&&Number.isFinite(value))return Math.max(0,value);const raw=String(value).trim();if(/^\d+(?:[.,]\d+)?$/.test(raw))return Math.max(0,Number(raw.replace(',','.')));const m=raw.match(/^(\d+):(\d{1,2})(?:[.,]\d+)?$/);return m?Number(m[1])*60+Number(m[2]):null;};
 const text=value=>ctx.esc(String(value??''));
 function configure(value){ctx=value;}
 function isOpen(id){return opened.has(id);}
 const score=x=>x!=null&&Number.isFinite(Number(x))?text(x):'—';
 const normalizeName=v=>String(v||'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
 function teamSide(d,i){const expected=normalizeName(i?d.team2:d.team1),rows=d.players||[];let row=rows.find(t=>normalizeName(t.name)===expected)||rows[i],side=String(row?.side||'').toLowerCase();if(['t','ct'].includes(side))return side;const other=rows[i?0:1],otherSide=String(other?.side||'').toLowerCase();return otherSide==='t'?'ct':otherSide==='ct'?'t':'';}
 const sideLabel=side=>side==='t'?'T':side==='ct'?'CT':'';
 function hasRoster(players){return Array.isArray(players)&&players.some(team=>Array.isArray(team?.members)&&team.members.some(player=>String(player?.name||'').trim()||player?.alive!=null||player?.k!=null||player?.d!=null||player?.a!=null));}
 function keepIfMissing(next,prev,key,valid){return valid(next?.[key])?next[key]:prev?.[key];}
 const own=(o,k)=>!!o&&Object.prototype.hasOwnProperty.call(o,k)&&o[k]!==undefined&&o[k]!==null;
 function mergeMembers(prev=[],next=[]){if(!Array.isArray(next)||!next.length)return Array.isArray(prev)?prev:[];const a=Array.isArray(prev)?prev:[],used=new Set(),out=next.map((row,index)=>{const name=normalizeName(row?.name),found=name?a.findIndex((old,i)=>!used.has(i)&&normalizeName(old?.name)===name):-1,slot=found>=0?found:(!used.has(index)&&a[index]?index:-1),old=slot>=0?a[slot]:{};if(slot>=0)used.add(slot);const merged={...old,...row};if(!String(row?.name||'').trim()&&String(old?.name||'').trim())merged.name=old.name;for(const key of ['k','a','d','alive'])if(!own(row,key)&&own(old,key))merged[key]=old[key];return merged;});for(let i=0;i<a.length;i++)if(!used.has(i))out.push(a[i]);return out;}
 function mergePlayers(prev=[],next=[]){if(!hasRoster(next))return Array.isArray(prev)?prev:[];const a=Array.isArray(prev)?prev:[],used=new Set(),out=next.map((team,index)=>{const name=normalizeName(team?.name),found=name?a.findIndex((old,i)=>!used.has(i)&&normalizeName(old?.name)===name):-1,slot=found>=0?found:(!used.has(index)&&a[index]?index:-1),old=slot>=0?a[slot]:{};if(slot>=0)used.add(slot);const merged={...old,...team,members:mergeMembers(old?.members,team?.members)};if(!String(team?.name||'').trim()&&String(old?.name||'').trim())merged.name=old.name;if(!String(team?.side||'').trim()&&String(old?.side||'').trim())merged.side=old.side;if(!own(team,'weaponsCost')&&own(old,'weaponsCost'))merged.weaponsCost=old.weaponsCost;return merged;});for(let i=0;i<a.length;i++)if(!used.has(i))out.push(a[i]);return out;}
 function mergeMapState(prev={},next={}){const merged={...prev,...next};merged.timeline=keepIfMissing(next,prev,'timeline',value=>Array.isArray(value)&&value.length);merged.eventLog=keepIfMissing(next,prev,'eventLog',value=>Array.isArray(value)&&value.length);merged.players=mergePlayers(prev?.players,next?.players);return merged;}
 function mergeState(prev,next){if(!prev)return next;if(!next)return prev;const mapChanged=prev?.mapNum!=null&&next?.mapNum!=null&&Number(prev.mapNum)!==Number(next.mapNum),base=mapChanged?{...prev,timeline:[],eventLog:[],players:[],currentRound:null,roundTime:null,bomb:null,roundScore:[null,null]}:prev,merged=mergeMapState(base,next);if(Array.isArray(prev.maps)||Array.isArray(next.maps)){const byNum=new Map((prev.maps||[]).map(map=>[map.mapNum,map]));for(const map of next.maps||[])byNum.set(map.mapNum,mergeMapState(byNum.get(map.mapNum)||{},map));merged.maps=[...byNum.values()].sort((a,b)=>Number(a.mapNum||0)-Number(b.mapNum||0));}return merged;}
 function logText(e,d){const team=e.team==='1'?d.team1:e.team==='2'?d.team2:'команда';switch(e.type){case 'death':return e.killer?`${e.killer} → ${e.player}`:`${e.player} погиб`;case 'bomb_planted':return 'Бомба установлена';case 'bomb_defusing':return 'Начато обезвреживание';case 'round_start':return 'Начался раунд';case 'side_switch':return `${team} теперь играет за ${sideLabel(e.side)||String(e.side||'').toUpperCase()}`;case 'round_end':return `${team} выиграла раунд · ${roundMethod(e.method).name}`;default:return e.type||'Событие';}}
 function logMarkup(d,s){const rows=(d.eventLog||[]).slice(-160).reverse();if(!rows.length)return '';return `<details class="fold cs2-fold cs2-event-log" data-cs2-log="${text(s.event.id)}" ${s.logOpen===true?'open':''}><summary>${UiKit.chevron('caret')}<span>Журнал событий</span><span class="n">${rows.length}</span></summary><div class="cs2-event-list">${rows.map((e,index)=>{const when=e.clock||Number(e.at)&&new Date(e.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})||'—';return `<div class="cs2-event-row" data-log-key="${text([e.at,e.type,e.round,e.player,index].join('-'))}"><time>R${text(e.round??'—')} · ${text(when)}</time><span>${text(logText(e,d))}</span></div>`;}).join('')}</div></details>`;}
 // Round outcome as the data states it; an unknown/absent type is only "won the round" (never guessed).
 const RI={
  eliminated:'<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 2.2a5.2 5.2 0 0 0-5.2 5.2c0 1.8.9 3.3 2.2 4.2v1.9h6v-1.9c1.3-.9 2.2-2.4 2.2-4.2A5.2 5.2 0 0 0 8 2.2z" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/><circle cx="6.1" cy="7.7" r="1.15" fill="currentColor"/><circle cx="9.9" cy="7.7" r="1.15" fill="currentColor"/></svg>',
  exploded:'<svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 1.6l1.4 3.5 3.5-1.6-1.6 3.5 3.5 1.4-3.5 1.4 1.6 3.5-3.5-1.6L8 15.2l-1.4-3.5-3.5 1.6 1.6-3.5L1.2 8.4l3.5-1.4-1.6-3.5 3.5 1.6z" fill="currentColor"/></svg>',
  defused:'<svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="4.6" cy="11.6" r="2.1" fill="none" stroke="currentColor" stroke-width="1.5"/><circle cx="11.4" cy="11.6" r="2.1" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M6 10 12.2 2.4M10 10 3.8 2.4" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>',
  timeout:'<svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="5.9" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M8 4.6V8l2.4 1.6" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>',
  won:'<svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="3.2" fill="currentColor"/></svg>'};
 function roundMethod(type){switch(String(type||'').toLowerCase()){case 'eliminated':case 'elimination':case 'kill':return {key:'eliminated',name:'Уничтожение команды',icon:RI.eliminated};case 'defused':case 'defuse':return {key:'defused',name:'Бомба обезврежена',icon:RI.defused};case 'exploded':case 'bomb':case 'explode':return {key:'exploded',name:'Взрыв бомбы',icon:RI.exploded};case 'time':case 'timeout':case 'time_out':return {key:'timeout',name:'Время раунда вышло',icon:RI.timeout};default:return {key:'won',name:'Победа в раунде (способ не передан)',icon:RI.won};}}
 // Time and phase: the live map reads the monotonic round clock (Cs2Clock); a saved/other map shows its stored time.
 function phaseInfo(d,clock){const bomb=d?.bomb,planted=['planted','defusing'].includes(bomb),archived=d?.archived||d?.finished;
  const live=clock&&!archived,seconds=live?clock.value():clockSeconds(d?.roundTime),stale=live?(clock.stale()||d?.connected===false):false;
  const phase=archived?'Сохранённая статистика':stale?'Нет свежих обновлений':planted?bomb==='defusing'?'Обезвреживание':'Бомба установлена':d?.timerRunning===false&&seconds!=null&&seconds<=35?'Закупка / пауза':d?.timerRunning===true||d?.clockAdvancing===true?'Раунд идёт':'Пауза';
  return {time:Cs2Clock.format(seconds),bomb:planted,phase,stale};}
 function header(s,d){const info=phaseInfo(d,s.clock);return `<div class="cs2-status" role="status"><span class="cs2-map">${text(d?.map||'Карта')}${d?.mapNum?` · карта ${score(d.mapNum)}`:''}${d?.mapScore?` · серия ${score(d.mapScore[0])}:${score(d.mapScore[1])}`:''}</span><span class="cs2-clock"><span data-cs2-round-label>Раунд ${score(d?.currentRound)}</span><strong data-cs2-time>${text(info.time)}</strong><span data-cs2-phase class="${info.bomb?'cs2-bomb':''}${info.stale?' is-stale':''}">${info.bomb?'● ':''}${text(info.phase)}</span></span></div>`;}
 function body(s){
  const raw=s.data,selected=s.map&&raw?.maps?.find(m=>m.mapNum===s.map),d=selected?{...raw,...selected,maps:raw.maps,archived:raw.archived||s.map!==raw.mapNum}:raw;
  if(!d)return `<p class="muted cs2-wait">${text(s.error||'Получаем табло…')}</p>`;
  if(!d.matched)return `<p class="muted cs2-wait">${text(d.error||'Нет точного совпадения в табло.')}</p>`;
  const rounds=d.timeline||[],chosen=rounds.find(r=>r.number===s.round)||rounds.at(-1),stale=!d.connected,sides=[teamSide(d,0),teamSide(d,1)];
  const winner=r=>r.team==='1'?d.team1:r.team==='2'?d.team2:'команда не указана';
  const roster=i=>{const want=normalizeName(i?d.team2:d.team1),list=(d.players||[]).filter(t=>t.members?.length);return list.find(t=>normalizeName(t.name)===want)||list[i];};
  const teamRow=i=>{const side=sides[i],t=roster(i),alive=t?.members?.filter(p=>p.alive===true).length,known=t?.members?.some(p=>p.alive!=null);
   return `<div class="cs2-team-row side-${side||'none'}"><span class="side-badge" title="${side==='ct'?'Контр-террористы':side==='t'?'Террористы':'Сторона неизвестна'}">${text(sideLabel(side)||'—')}</span><strong class="cs2-name" title="${text(i?d.team2:d.team1)}">${text(i?d.team2:d.team1)}</strong>${known?`<span class="alive" title="Живы: ${alive} из ${t.members.length}" aria-label="Живы ${alive} из ${t.members.length}">${t.members.map(p=>`<i class="${p.alive===true?'on':p.alive===false?'off':'unk'}"></i>`).join('')}</span>`:''}${Number(t?.weaponsCost)>0?`<span class="econ" title="Стоимость снаряжения">$${text(Number(t.weaponsCost).toLocaleString('ru-RU'))}</span>`:''}<b class="cs2-rs num">${score(d.roundScore?.[i])}</b></div>`;};
  const mapTabs=d.maps?.length>1?`<div class="cs2-maps" role="group" aria-label="Карты">${d.maps.map(m=>{const rs=Array.isArray(m.roundScore)&&m.roundScore.every(x=>x!=null)?` · ${m.roundScore[0]}:${m.roundScore[1]}`:'',current=m.mapNum===raw.mapNum&&!raw.archived;return `<button type="button" data-cs2-map="${m.mapNum}" data-cs2-id="${text(s.event.id)}" aria-pressed="${(s.map||raw.mapNum)===m.mapNum}">${current?'<span class="dot bad" aria-hidden="true"></span>':''}Карта ${m.mapNum}${m.map?' · '+text(m.map):''}${rs}</button>`;}).join('')}</div>`:'';
  const used=new Set();
  const live=!d.archived&&!d.finished&&Number(d.currentRound)>0&&!rounds.some(r=>r.number===Number(d.currentRound));
  const col=r=>{const m=roundMethod(r.type),side=String(r.side||'').toLowerCase();used.add(m.key);return `<button type="button" data-cs2-round="${r.number}" data-cs2-id="${text(s.event.id)}" class="rc${r.number===13||(r.number>24&&(r.number-25)%3===0)?' half':''}" title="Раунд ${r.number}: ${text(winner(r))} · ${text(m.name)}${side?' · '+text(sideLabel(side)):''}" aria-label="Раунд ${r.number}: ${text(winner(r))}, ${text(m.name)}" aria-pressed="${chosen?.number===r.number}"><small>${r.number}</small>${['1','2'].map(team=>r.team===team?`<span class="slot won ${side==='ct'||side==='t'?side:'nside'}">${m.icon}</span>`:'<span class="slot"></span>').join('')}</button>`;};
  const track=rounds.map(col).join('')+(live?`<span class="rc current" title="Раунд ${score(d.currentRound)} идёт"><small>${score(d.currentRound)}</small><span class="slot"></span><span class="slot"></span></span>`:'');
  const legend=['eliminated','exploded','defused','timeout','won'].filter(k=>used.has(k)).map(k=>{const m=roundMethod(k==='won'?'':k);return `<span>${m.icon}${text(k==='won'?'способ не передан':m.name.toLowerCase())}</span>`;}).join('');
  const roundsMarkup=rounds.length||live?`<div class="cs2-rounds-block"><div class="cs2-round-names" aria-hidden="true"><small>Раунд</small><b class="side-${sides[0]||'none'}">${text(d.team1)}</b><b class="side-${sides[1]||'none'}">${text(d.team2)}</b></div><div class="cs2-track" role="group" aria-label="История раундов">${track}</div></div>${chosen?`<div class="cs2-round-detail">Раунд ${chosen.number} · <b>${text(winner(chosen))}</b> · ${text(roundMethod(chosen.type).name)}</div>`:''}${legend?`<div class="cs2-legend" aria-label="Обозначения">${legend}<span class="sides"><i class="ct"></i>CT <i class="t"></i>T</span></div>`:''}`:'<p class="muted">Раунды пока не завершены.</p>';
  const players=(d.players||[]).filter(t=>t.members?.length).map((team,index)=>{const side=String(team.side||'').toLowerCase();return `<section class="cs2-roster side-${text(side||'none')}"><div class="cs2-roster-head"><b>${text(team.name||(index?d.team2:d.team1))}</b><small>${text(sideLabel(side))}</small></div><div class="cs2-pl-head" aria-hidden="true"><span></span><span>Игрок</span><span>K</span><span>A</span><span>D</span></div>${team.members.map(p=>`<div class="cs2-player ${p.alive===true?'alive':p.alive===false?'dead':'unknown'}"><i title="${p.alive===true?'Жив':p.alive===false?'Выбыл':'Неизвестно'}" aria-label="${p.alive===true?'Жив':p.alive===false?'Выбыл':'Неизвестно'}"></i><span class="pn">${text(p.name)}</span><span class="num">${score(p.k)}</span><span class="num">${score(p.a)}</span><span class="num">${score(p.d)}</span></div>`).join('')}</section>`;}).join('');
  return `${mapTabs}<div class="cs2-board">${header(s,d)}<div class="cs2-teams">${teamRow(0)}${teamRow(1)}</div></div>
  <div class="cs2-section">${roundsMarkup}</div>
  ${players?`<details class="fold cs2-fold" data-cs2-players="${text(s.event.id)}" ${s.playersOpen?'open':''}><summary>${UiKit.chevron('caret')}<span>Игроки</span><span class="n">K / A / D · живые и выбывшие</span></summary><div class="cs2-rosters">${players}</div></details>`:''}
  ${logMarkup(d,s)}
  ${UiKit.streamLinks(d.streamLinks)}
  <small class="muted cs2-updated">${stale?'Соединение прервано · ':''}Обновлено ${new Date(d.updatedAt).toLocaleTimeString('ru-RU')}</small>`;
 }
 function markup(e){const s=opened.get(e.id);if(s)s.event=e;return s?`<section class="cs2-panel" data-cs2-body="${text(e.id)}">${body(s)}</section>`:'';}
 function panelFor(s){let panel=s.panel;if(!panel?.isConnected||panel.dataset.cs2Body!==String(s.event.id))panel=s.panel=document.querySelector('[data-cs2-body="'+CSS.escape(String(s.event.id))+'"]');return panel;}
 function tick(s){const panel=panelFor(s),d=s.data;if(!panel||!d?.matched)return;const shown=s.map&&d.maps?.find(m=>m.mapNum===s.map)?{...d,...d.maps.find(m=>m.mapNum===s.map),archived:d.archived||s.map!==d.mapNum}:d,info=phaseInfo(shown,s.clock),time=panel.querySelector('[data-cs2-time]'),phase=panel.querySelector('[data-cs2-phase]'),label=panel.querySelector('[data-cs2-round-label]'),updated=panel.querySelector('.cs2-updated');
  if(time&&time.textContent!==info.time)time.textContent=info.time;if(label){const value='Раунд '+(shown.currentRound??'—');if(label.textContent!==value)label.textContent=value;}if(phase){const value=(info.bomb?'● ':'')+info.phase;if(phase.textContent!==value)phase.textContent=value;phase.classList.toggle('cs2-bomb',info.bomb);phase.classList.toggle('is-stale',info.stale);}if(updated){const value=(d.archived||d.finished?'Архив · ':s.error?'Ошибка связи · ':d.connected?'':'Соединение прервано · ')+'Обновлено '+new Date(d.updatedAt).toLocaleTimeString('ru-RU');if(updated.textContent!==value)updated.textContent=value;}}
 function paint(s){const panel=panelFor(s);if(!panel)return;const d=s.data,key=JSON.stringify([ctx.logosEnabled?.()!==false,d?.matched,d?.error,d?.roundScore,d?.mapScore,d?.map,d?.mapNum,d?.currentRound,d?.timeline,d?.eventLog,d?.players,d?.streamLinks,s.round,s.map,s.error]);
  if(key!==s.renderKey){s.playersOpen=panel.querySelector('[data-cs2-players]')?.open??s.playersOpen;s.logOpen=panel.querySelector('.cs2-event-log')?.open??s.logOpen;const track=panel.querySelector('.cs2-track'),scroll=track?.scrollLeft||0,atEnd=track?track.scrollLeft+track.clientWidth>=track.scrollWidth-4:true;s.renderKey=key;StableDOM.patch(panel,body(s));const list=panel.querySelector('.cs2-track');if(list)list.scrollLeft=atEnd?list.scrollWidth:scroll;}tick(s);}
 function schedulePaint(s,immediate=false){if(!s)return;if(immediate){clearTimeout(s.paintTimer);s.paintTimer=0;s.paintQueued=false;s.lastPaintAt=performance.now();paint(s);return;}if(s.paintQueued)return;s.paintQueued=true;const wait=Math.max(0,180-(performance.now()-(s.lastPaintAt||0)));s.paintTimer=setTimeout(()=>{s.paintTimer=0;requestAnimationFrame(()=>{s.paintQueued=false;if(!opened.has(s.event.id))return;s.lastPaintAt=performance.now();paint(s);});},wait);}
 async function refresh(id){const s=opened.get(id);if(!s||s.loading)return;s.loading=true;
  try{const data=await StatisticsClient.get(s.event);if(opened.get(id)!==s)return;if(data.matched){ctx.learnLogos?.({category:s.event.category,team1:data.team1,team2:data.team2,team1Logo:data.team1Logo,team2Logo:data.team2Logo});s.data=mergeState(s.data,{...data,receivedAt:Date.now()});s.clock.update(s.data,{receivedLocal:performance.now()});}s.error='';}
  catch(error){s.error=error.message;}finally{s.loading=false;if(opened.get(id)===s)schedulePaint(s,true);}
 }
 // One timer per open panel, due exactly when the shown second changes (no fixed 1 s interval to drift against).
 function scheduleTick(s){clearTimeout(s.tickTimer);const ms=document.hidden?1000:(s.clock?.nextChangeIn()??1000);s.tickTimer=setTimeout(()=>{if(!opened.has(s.event.id))return;if(!document.hidden&&s.data)tick(s);scheduleTick(s);},ms);}
 function toggle(event){const old=opened.get(event.id);if(old){old.unsubscribe?.();clearTimeout(old.paintTimer);clearTimeout(old.tickTimer);opened.delete(event.id);ctx.render();return;}opened.set(event.id,{event,data:null,error:'',round:0,playersOpen:true,logOpen:false,lastStreamAt:0,panel:null,clock:Cs2Clock.createRoundClock(),tickTimer:0});const state=opened.get(event.id);scheduleTick(state);state.unsubscribe=StatisticsClient.subscribe(event,data=>{if(opened.get(event.id)!==state)return;state.lastStreamAt=Date.now();state.data=mergeState(state.data,data);state.clock.update(state.data,{receivedLocal:performance.now()});state.error='';schedulePaint(state);});ctx.render();refresh(event.id);}
 document.addEventListener('click',event=>{const map=event.target.closest('[data-cs2-map]');if(map){const s=opened.get(map.dataset.cs2Id);if(s){s.map=Number(map.dataset.cs2Map);schedulePaint(s,true);}return;}const b=event.target.closest('[data-cs2-round]');if(!b)return;const s=opened.get(b.dataset.cs2Id);if(s){s.round=Number(b.dataset.cs2Round);schedulePaint(s,true);}});
 document.addEventListener('toggle',event=>{const playerId=event.target?.dataset?.cs2Players,logId=event.target?.dataset?.cs2Log;if(playerId){const s=opened.get(playerId);if(s)s.playersOpen=event.target.open;}if(logId){const s=opened.get(logId);if(s)s.logOpen=event.target.open;}},true);
 setInterval(()=>{if(document.hidden)return;for(const [id,s] of opened){if(!s.event?.inLive)continue;const panel=s.panel?.isConnected?s.panel:document.querySelector('[data-cs2-body="'+CSS.escape(String(id))+'"]');if(panel&&Date.now()-(s.lastStreamAt||0)>12000)refresh(id);}},15000);
 window.addEventListener('pagehide',()=>{for(const s of opened.values()){s.unsubscribe?.();clearTimeout(s.paintTimer);clearTimeout(s.tickTimer);}opened.clear();});
 function clear(){for(const s of opened.values()){s.unsubscribe?.();clearTimeout(s.paintTimer);clearTimeout(s.tickTimer);}opened.clear();}
 function refreshAppearance(){for(const s of opened.values()){s.renderKey='';schedulePaint(s,true);}}
 return {configure,isOpen,toggle,markup,refreshAppearance,clear,openCount:()=>opened.size};
})();
