const Cs2Panel=(()=>{
 const opened=new Map();let ctx;
 const clockSeconds=value=>{if(value==null||value==='')return null;if(typeof value==='number'&&Number.isFinite(value))return Math.max(0,value);const raw=String(value).trim();if(/^\d+(?:[.,]\d+)?$/.test(raw))return Math.max(0,Number(raw.replace(',','.')));const m=raw.match(/^(\d+):(\d{1,2})(?:[.,]\d+)?$/);return m?Number(m[1])*60+Number(m[2]):null;};
 const text=value=>ctx.esc(String(value??''));
 const icon=url=>{let host='';try{host=new URL(url).hostname;}catch{}return host.includes('twitch')?{kind:'twitch',label:'Twitch',svg:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 3h17v12l-5 5h-4l-3 3v-3H4V3zm2 2v13h4v2l2-2h4l3-3V5H6zm5 3h2v6h-2V8zm4 0h2v6h-2V8z"/></svg>'}:host.includes('kick')?{kind:'kick',label:'Kick',svg:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h6v6h2V8h2V6h6v6h-3v2h3v6h-6v-2h-2v-2h-2v4H4V4z"/></svg>'}:{kind:'other',label:'Трансляция',svg:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14l11-7L8 5z"/></svg>'};};
 const checkedLogo=value=>{const local=StatisticsClient.logo(value);if(local!==value)return local;try{const u=new URL(value);return u.protocol==='https:'&&['cdn.cross.bet','v2l.traincdn.com'].includes(u.hostname)?u.href:'';}catch{return '';}};
 function configure(value){ctx=value;}
 function isOpen(id){return opened.has(id);}
 function teamLogo(d,s,i){const normalize=v=>String(v||'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,''),exact=normalize(d.team1)===normalize(s.event.team1)&&normalize(d.team2)===normalize(s.event.team2),swapped=normalize(d.team1)===normalize(s.event.team2)&&normalize(d.team2)===normalize(s.event.team1);
  const fromAstek=s.event?.team1Logo&&s.event?.team2Logo&&(exact||swapped),a=swapped?i?0:1:i;
  if(ctx.logosEnabled?.()===false)return '';const url=checkedLogo(fromAstek?(a?s.event.team2Logo:s.event.team1Logo):(i?d.team2Logo:d.team1Logo));return url?`<img class="cs2-logo" src="${text(url)}" alt="" aria-hidden="true" draggable="false" loading="eager" decoding="async">`:'<span class="cs2-logo fallback">'+text(String(i?d.team2:d.team1).slice(0,2).toUpperCase())+'</span>';}
 const score=x=>x!=null&&Number.isFinite(Number(x))?text(x):'—';
 const normalizeName=v=>String(v||'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
 function teamSide(d,i){const expected=normalizeName(i?d.team2:d.team1),rows=d.players||[];let row=rows.find(t=>normalizeName(t.name)===expected)||rows[i],side=String(row?.side||'').toLowerCase();if(['t','ct'].includes(side))return side;const other=rows[i?0:1],otherSide=String(other?.side||'').toLowerCase();return otherSide==='t'?'ct':otherSide==='ct'?'t':'';}
 const sideLabel=side=>side==='t'?'T':side==='ct'?'CT':'';
 function hasRoster(players){return Array.isArray(players)&&players.some(team=>Array.isArray(team?.members)&&team.members.some(player=>String(player?.name||'').trim()||player?.alive!=null||player?.k!=null||player?.d!=null||player?.a!=null));}
 function keepIfMissing(next,prev,key,valid){return valid(next?.[key])?next[key]:prev?.[key];}
 const own=(o,k)=>!!o&&Object.prototype.hasOwnProperty.call(o,k)&&o[k]!==undefined&&o[k]!==null;
 function mergeMembers(prev=[],next=[]){if(!Array.isArray(next)||!next.length)return Array.isArray(prev)?prev:[];const a=Array.isArray(prev)?prev:[],used=new Set(),out=next.map((row,index)=>{const name=normalizeName(row?.name),found=name?a.findIndex((old,i)=>!used.has(i)&&normalizeName(old?.name)===name):-1,slot=found>=0?found:(!used.has(index)&&a[index]?index:-1),old=slot>=0?a[slot]:{};if(slot>=0)used.add(slot);const merged={...old,...row};if(!String(row?.name||'').trim()&&String(old?.name||'').trim())merged.name=old.name;for(const key of ['k','a','d','alive'])if(!own(row,key)&&own(old,key))merged[key]=old[key];return merged;});for(let i=0;i<a.length;i++)if(!used.has(i))out.push(a[i]);return out;}
 function mergePlayers(prev=[],next=[]){if(!hasRoster(next))return Array.isArray(prev)?prev:[];const a=Array.isArray(prev)?prev:[],used=new Set(),out=next.map((team,index)=>{const name=normalizeName(team?.name),found=name?a.findIndex((old,i)=>!used.has(i)&&normalizeName(old?.name)===name):-1,slot=found>=0?found:(!used.has(index)&&a[index]?index:-1),old=slot>=0?a[slot]:{};if(slot>=0)used.add(slot);const merged={...old,...team,members:mergeMembers(old?.members,team?.members)};if(!String(team?.name||'').trim()&&String(old?.name||'').trim())merged.name=old.name;if(!String(team?.side||'').trim()&&String(old?.side||'').trim())merged.side=old.side;if(!own(team,'weaponsCost')&&own(old,'weaponsCost'))merged.weaponsCost=old.weaponsCost;return merged;});for(let i=0;i<a.length;i++)if(!used.has(i))out.push(a[i]);return out;}
 function mergeMapState(prev={},next={}){const merged={...prev,...next};merged.timeline=keepIfMissing(next,prev,'timeline',value=>Array.isArray(value)&&value.length);merged.eventLog=keepIfMissing(next,prev,'eventLog',value=>Array.isArray(value)&&value.length);merged.players=mergePlayers(prev?.players,next?.players);return merged;}
 function mergeState(prev,next){if(!prev)return next;if(!next)return prev;const mapChanged=prev?.mapNum!=null&&next?.mapNum!=null&&Number(prev.mapNum)!==Number(next.mapNum),base=mapChanged?{...prev,timeline:[],eventLog:[],players:[],currentRound:null,roundTime:null,bomb:null,roundScore:[null,null]}:prev,merged=mergeMapState(base,next);if(Array.isArray(prev.maps)||Array.isArray(next.maps)){const byNum=new Map((prev.maps||[]).map(map=>[map.mapNum,map]));for(const map of next.maps||[])byNum.set(map.mapNum,mergeMapState(byNum.get(map.mapNum)||{},map));merged.maps=[...byNum.values()].sort((a,b)=>Number(a.mapNum||0)-Number(b.mapNum||0));}return merged;}
 function logText(e,d){const team=e.team==='1'?d.team1:e.team==='2'?d.team2:'команда';switch(e.type){case 'death':return e.killer?`${e.killer} → ${e.player}`:`${e.player} погиб`;case 'bomb_planted':return 'Бомба установлена';case 'bomb_defusing':return 'Начато обезвреживание';case 'round_start':return 'Начался раунд';case 'side_switch':return `${team} теперь играет за ${sideLabel(e.side)||String(e.side||'').toUpperCase()}`;case 'round_end':return `${team} выиграла раунд · ${roundMethod(e.method).name}`;default:return e.type||'Событие';}}
 function logMarkup(d,s){const rows=(d.eventLog||[]).slice(-160).reverse();if(!rows.length)return '';return `<details class="cs2-event-log" data-cs2-log="${text(s.event.id)}" ${s.logOpen!==false?'open':''}><summary>Журнал событий · ${rows.length}</summary><div class="cs2-event-list">${rows.map((e,index)=>{const when=e.clock||Number(e.at)&&new Date(e.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})||'—';return `<div class="cs2-event-row" data-log-key="${text([e.at,e.type,e.round,e.player,index].join('-'))}"><time>R${text(e.round??'—')} · ${text(when)}</time><span>${text(logText(e,d))}</span></div>`;}).join('')}</div></details>`;}
 function roundMethod(type){switch(String(type||'').toLowerCase()){case 'eliminated':return {name:'Уничтожение команды',icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17v4h10v-4c3-2 4-4 4-7a9 9 0 0 0-18 0c0 3 1 5 4 7Z"/><path d="M9 18v3m3-3v3m3-3v3M8 10h1m6 0h1m-5 5h2"/></svg>'};case 'defused':return {name:'Обезвреживание бомбы',icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 3 5 5-3 3-5-5m8 2 10 11-3 3L7 11m11-9-3 3 4 4 3-3m-5 3L3 21"/></svg>'};case 'exploded':case 'bomb':return {name:'Взрыв бомбы',icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 2 7 6-5-3 8 5 3-8 1-2 6-3-6-7 1 5-6-3-6 6 4Z"/></svg>'};case 'time':case 'timeout':return {name:'Время вышло',icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 6v7h5"/></svg>'};default:return {name:'Победа в раунде',icon:'✓'};}}
 // Time and phase: the live map reads the monotonic round clock (Cs2Clock); a saved/other map shows its stored time.
 function phaseInfo(d,clock){const bomb=d?.bomb,planted=['planted','defusing'].includes(bomb),archived=d?.archived||d?.finished;
  const live=clock&&!archived,seconds=live?clock.value():clockSeconds(d?.roundTime),stale=live?(clock.stale()||d?.connected===false):false;
  const phase=archived?'Сохранённая статистика':stale?'Нет свежих обновлений':planted?bomb==='defusing'?'Обезвреживание':'Бомба установлена':d?.timerRunning===false&&seconds!=null&&seconds<=35?'Закупка / пауза':d?.timerRunning===true||d?.clockAdvancing===true?'Раунд идёт':'Пауза';
  return {time:Cs2Clock.format(seconds),bomb:planted,phase,stale};}
 function header(s,d){const info=phaseInfo(d,s.clock);return `<div class="cs2-heading"><b>Статистика CS2</b><div class="cs2-clock"><span data-cs2-round-label>Раунд ${score(d?.currentRound)}</span><strong data-cs2-time>${text(info.time)}</strong><span data-cs2-phase class="${info.bomb?'cs2-bomb':''}">${info.bomb?'● ':''}${text(info.phase)}</span></div><button data-cs2-close="${text(s.event.id)}" class="cs2-close" aria-label="Скрыть статистику">×</button></div>`;}
 function body(s){
  const raw=s.data,selected=s.map&&raw?.maps?.find(m=>m.mapNum===s.map),d=selected?{...raw,...selected,maps:raw.maps,archived:raw.archived||s.map!==raw.mapNum}:raw;
  if(!d)return `${header(s)}<p class="muted">${text(s.error||'Получаем табло…')}</p>`;
  if(!d.matched)return `${header(s)}<p class="muted">${text(d.error||'Нет точного совпадения в табло.')}</p>`;
  const rounds=d.timeline||[],chosen=rounds.find(r=>r.number===s.round)||rounds.at(-1),stale=!d.connected,sides=[teamSide(d,0),teamSide(d,1)];
  const winner=r=>r.team==='1'?d.team1:r.team==='2'?d.team2:'Команда не указана';
  const players=(d.players||[]).filter(t=>t.members?.length).map((team,index)=>`<section class="cs2-team-players side-${text(String(team.side||'').toLowerCase())}"><div><b>${text(team.name||(index?d.team2:d.team1))}</b><small>${text(String(team.side||'').toUpperCase())}${Number(team.weaponsCost)>0?' · $'+text(team.weaponsCost):''}</small></div>${team.members.map(p=>`<div class="cs2-player ${p.alive===true?'alive':p.alive===false?'dead':'unknown'}"><i aria-label="${p.alive===true?'Жив':p.alive===false?'Выбыл':'Неизвестно'}">${p.alive===true?'●':p.alive===false?'✕':'?'}</i><span>${text(p.name)}</span><small>${score(p.k)}/${score(p.a)}/${score(p.d)}</small></div>`).join('')}</section>`).join('');
  const mapTabs=d.maps?.length>1?`<div class="hawk-maps">${d.maps.map(m=>`<button data-cs2-map="${m.mapNum}" data-cs2-id="${text(s.event.id)}" aria-pressed="${(s.map||raw.mapNum)===m.mapNum}">Карта ${m.mapNum}${m.map?' · '+text(m.map):''}</button>`).join('')}</div>`:'';
  const roundsMarkup=rounds.length?`<div class="cs2-round-block"><div class="cs2-round-labels"><small>Раунд</small><b>${text(d.team1)}</b><b>${text(d.team2)}</b></div><div class="cs2-rounds cs2-round-track" aria-label="История раундов">${rounds.map(r=>`<button type="button" data-cs2-round="${r.number}" data-cs2-id="${text(s.event.id)}" class="round-column ${r.number===13||(r.number>24&&(r.number-25)%3===0)?'half-start':''}" aria-label="Раунд ${r.number}: ${text(winner(r))}, ${text(roundMethod(r.type).name)}" aria-pressed="${chosen?.number===r.number}"><small>${r.number}</small>${['1','2'].map(team=>`<span class="round-slot ${r.team===team?'won '+text(String(r.side).toLowerCase()):''}">${r.team===team?roundMethod(r.type).icon:'·'}</span>`).join('')}</button>`).join('')}</div></div><div class="cs2-round-detail">Раунд ${chosen.number} · <b>${text(winner(chosen))}</b> · ${text(roundMethod(chosen.type).name)}</div>`:'<p class="muted">Раунды пока не завершены.</p>';
  return `${header(s,d)}${mapTabs}<div class="cs2-scoreboard"><div class="cs2-team side-${sides[0]} ${ctx.logosEnabled?.()===false?'no-logo':''}">${teamLogo(d,s,0)}<strong class="cs2-dup-name">${text(d.team1)}</strong><small>${text(sideLabel(sides[0]))}</small></div><div class="cs2-center"><b>${score(d.roundScore?.[0])} : ${score(d.roundScore?.[1])}</b><span>${text(d.map||'Карта не указана')} · карта ${score(d.mapNum)}</span><small>Серия ${score(d.mapScore?.[0])}:${score(d.mapScore?.[1])}</small></div><div class="cs2-team away side-${sides[1]} ${ctx.logosEnabled?.()===false?'no-logo':''}">${teamLogo(d,s,1)}<strong class="cs2-dup-name">${text(d.team2)}</strong><small>${text(sideLabel(sides[1]))}</small></div></div>
  ${roundsMarkup}${logMarkup(d,s)}
  ${players.length?`<details class="cs2-players" data-cs2-players="${text(s.event.id)}" ${s.playersOpen?'open':''}><summary>Игроки · живые и выбывшие</summary><div class="cs2-rosters">${players}</div></details>`:''}
  <div class="hawk-streams cs2-streams">${d.streamLinks?.length?`<span class="hawk-streams-label">Трансляции</span>${d.streamLinks.map(link=>{const i=icon(link.url);return `<button class="hawk-stream-button ${i.kind}" data-open-url="${text(link.url)}" aria-label="${i.label} · ${text(link.name)}">${i.svg}<span>${text(link.name||i.label)}</span></button>`;}).join('')}`:'<span class="muted">Трансляций нет</span>'}</div><small class="muted cs2-updated">${stale?'Соединение прервано · ':''}Обновлено ${new Date(d.updatedAt).toLocaleTimeString('ru-RU')}</small>`;
 }
 function markup(e){const s=opened.get(e.id);if(s)s.event=e;return s?`<section class="cs2-panel hawk-panel" data-cs2-body="${text(e.id)}">${body(s)}</section>`:'';}
 function panelFor(s){let panel=s.panel;if(!panel?.isConnected||panel.dataset.cs2Body!==String(s.event.id))panel=s.panel=document.querySelector('[data-cs2-body="'+CSS.escape(String(s.event.id))+'"]');return panel;}
 function tick(s){const panel=panelFor(s),d=s.data;if(!panel||!d?.matched)return;const shown=s.map&&d.maps?.find(m=>m.mapNum===s.map)?{...d,...d.maps.find(m=>m.mapNum===s.map),archived:d.archived||s.map!==d.mapNum}:d,info=phaseInfo(shown,s.clock),time=panel.querySelector('[data-cs2-time]'),phase=panel.querySelector('[data-cs2-phase]'),label=panel.querySelector('[data-cs2-round-label]'),updated=panel.querySelector('.cs2-updated');
  if(time&&time.textContent!==info.time)time.textContent=info.time;if(label){const value='Раунд '+(shown.currentRound??'—');if(label.textContent!==value)label.textContent=value;}if(phase){const value=(info.bomb?'● ':'')+info.phase;if(phase.textContent!==value)phase.textContent=value;phase.classList.toggle('cs2-bomb',info.bomb);phase.classList.toggle('is-stale',info.stale);}if(updated){const value=(d.archived||d.finished?'Архив · ':s.error?'Ошибка связи · ':d.connected?'':'Соединение прервано · ')+'Обновлено '+new Date(d.updatedAt).toLocaleTimeString('ru-RU');if(updated.textContent!==value)updated.textContent=value;}}
 function paint(s){const panel=panelFor(s);if(!panel)return;const d=s.data,key=JSON.stringify([ctx.logosEnabled?.()!==false,d?.matched,d?.error,d?.roundScore,d?.mapScore,d?.map,d?.mapNum,d?.currentRound,d?.timeline,d?.eventLog,d?.players,d?.streamLinks,s.round,s.map,s.error]);
  if(key!==s.renderKey){s.playersOpen=panel.querySelector('.cs2-players')?.open??s.playersOpen;s.logOpen=panel.querySelector('.cs2-event-log')?.open??s.logOpen;const scroll=panel.querySelector('.cs2-rounds')?.scrollLeft||0;s.renderKey=key;StableDOM.patch(panel,body(s));const list=panel.querySelector('.cs2-rounds');if(list)list.scrollLeft=scroll;}tick(s);}
 function schedulePaint(s,immediate=false){if(!s)return;if(immediate){clearTimeout(s.paintTimer);s.paintTimer=0;s.paintQueued=false;s.lastPaintAt=performance.now();paint(s);return;}if(s.paintQueued)return;s.paintQueued=true;const wait=Math.max(0,180-(performance.now()-(s.lastPaintAt||0)));s.paintTimer=setTimeout(()=>{s.paintTimer=0;requestAnimationFrame(()=>{s.paintQueued=false;if(!opened.has(s.event.id))return;s.lastPaintAt=performance.now();paint(s);});},wait);}
 async function refresh(id){const s=opened.get(id);if(!s||s.loading)return;s.loading=true;
  try{const data=await StatisticsClient.get(s.event);if(opened.get(id)!==s)return;if(data.matched){s.data=mergeState(s.data,{...data,receivedAt:Date.now()});s.clock.update(s.data,{receivedLocal:performance.now()});}s.error='';}
  catch(error){s.error=error.message;}finally{s.loading=false;if(opened.get(id)===s)schedulePaint(s,true);}
 }
 // One timer per open panel, due exactly when the shown second changes (no fixed 1 s interval to drift against).
 function scheduleTick(s){clearTimeout(s.tickTimer);const ms=document.hidden?1000:(s.clock?.nextChangeIn()??1000);s.tickTimer=setTimeout(()=>{if(!opened.has(s.event.id))return;if(!document.hidden&&s.data)tick(s);scheduleTick(s);},ms);}
 function toggle(event){const old=opened.get(event.id);if(old){old.unsubscribe?.();clearTimeout(old.paintTimer);clearTimeout(old.tickTimer);opened.delete(event.id);ctx.render();return;}opened.set(event.id,{event,data:null,error:'',round:0,playersOpen:true,logOpen:true,lastStreamAt:0,panel:null,clock:Cs2Clock.createRoundClock(),tickTimer:0});const state=opened.get(event.id);scheduleTick(state);state.unsubscribe=StatisticsClient.subscribe(event,data=>{if(opened.get(event.id)!==state)return;state.lastStreamAt=Date.now();state.data=mergeState(state.data,data);state.clock.update(state.data,{receivedLocal:performance.now()});state.error='';schedulePaint(state);});ctx.render();refresh(event.id);}
 document.addEventListener('click',event=>{const map=event.target.closest('[data-cs2-map]');if(map){const s=opened.get(map.dataset.cs2Id);if(s){s.map=Number(map.dataset.cs2Map);schedulePaint(s,true);}return;}const b=event.target.closest('[data-cs2-round]');if(!b)return;const s=opened.get(b.dataset.cs2Id);if(s){s.round=Number(b.dataset.cs2Round);schedulePaint(s,true);}});
 document.addEventListener('toggle',event=>{const playerId=event.target?.dataset?.cs2Players,logId=event.target?.dataset?.cs2Log;if(playerId){const s=opened.get(playerId);if(s)s.playersOpen=event.target.open;}if(logId){const s=opened.get(logId);if(s)s.logOpen=event.target.open;}},true);
 setInterval(()=>{if(document.hidden)return;for(const [id,s] of opened){if(!s.event?.inLive)continue;const panel=s.panel?.isConnected?s.panel:document.querySelector('[data-cs2-body="'+CSS.escape(String(id))+'"]');if(panel&&Date.now()-(s.lastStreamAt||0)>12000)refresh(id);}},15000);
 window.addEventListener('pagehide',()=>{for(const s of opened.values()){s.unsubscribe?.();clearTimeout(s.paintTimer);clearTimeout(s.tickTimer);}opened.clear();});
 function clear(){for(const s of opened.values()){s.unsubscribe?.();clearTimeout(s.paintTimer);clearTimeout(s.tickTimer);}opened.clear();}
 function refreshAppearance(){for(const s of opened.values()){s.renderKey='';schedulePaint(s,true);}}
 return {configure,isOpen,toggle,markup,refreshAppearance,clear,openCount:()=>opened.size};
})();
