/* Common score/odds timeline. API pagination is per visible change, not per snapshot. */
(function(root){
 const names={astek:'AstekBet',fonbet:'Fonbet',pinnacle:'Pinnacle',ggbet:'GGBET','ggbet-browser':'GGBET Browser','ggbet-node':'GGBET Node'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const value=v=>v==null||v===''?'—':typeof v==='object'?JSON.stringify(v):String(v);
 function rows(entries){return entries.map(e=>`<tr data-history-id="${esc(e.id)}"><td><time datetime="${esc(e.timestamp)}">${esc(new Date(e.at).toISOString().slice(11,19))}</time><br><small>${esc(new Date(e.at).toISOString().slice(0,10))}</small></td><td>${esc(names[e.publicationSource]||names[e.provider]||e.provider)}</td><td>${e.kind==='score'?'Счёт':e.kind==='state'?'Состояние матча':esc(e.marketName||e.marketId||'Рынок')}${e.kind==='odds'?'<br><small>'+esc(e.outcomeName||e.outcomeId)+'</small>':''}${e.map||e.period?'<br><small>Карта / период '+esc(e.map||e.period)+'</small>':''}</td><td>${e.baseline?'<small>Первое наблюдение</small><br>':esc(value(e.oldValue))+' → '}${esc(value(e.newValue))}${e.kind==='market'?'<small> · статус рынка</small>':''}</td></tr>`).join('');}
 function url(event,provider='',cursor=''){const keys=[...new Set((event.sourceRefs?.length?event.sourceRefs:[event]).flatMap(r=>[r.source+':'+String(r.sourceEventId||r.id||'').replace(/^fonbet-(?:result-)?/,''),...(r.aliases||[])]))];return '/api/events/'+encodeURIComponent(event.id)+'/history?'+new URLSearchParams({ids:keys.join(','),limit:'100',...(provider?{provider}:{}),...(cursor?{cursor}:{})});}
 function open(event,{modal,request}){
  let generation=0,provider='',entries=[],next=null,closed=false,loading=false,browsingOlder=false;
  modal(`<div class="data-dialog-header"><div><h2>История</h2><strong>${esc(event.team1)} — ${esc(event.team2)}</strong></div><button id="historyClose" class="icon-button" aria-label="Закрыть">×</button></div><div class="score-controls" id="historyFilters">${['','astek','fonbet','pinnacle','ggbet'].map(p=>`<button data-history-provider="${p}" aria-pressed="${p===''}">${names[p]||'Все'}</button>`).join('')}<button id="historyRefresh">Обновить</button></div><p class="dialog-caption muted">Время записи · UTC. GGBET Browser и Node показаны как отдельные источники.</p><p id="historyStatus" role="status">Загружаем…</p><div class="history-table-wrap"><table class="score-table"><thead><tr><th>Время</th><th>Букмекер</th><th>Счёт / рынок / исход</th><th>Изменение</th></tr></thead><tbody id="historyEntries"></tbody></table></div><button id="historyMore" hidden>Показать ещё</button>`,'match-history');
  const $=id=>document.getElementById(id),active=()=>!closed&&$('modal').open&&$('modal').dataset.kind==='match-history';
  $('historyClose').onclick=()=>$('modal').close();$('modal').addEventListener('close',()=>{closed=true;clearInterval(autoRefresh);++generation;},{once:true});
  async function load(more=false){browsingOlder=more||false;const token=++generation;loading=true;$('historyMore').disabled=true;$('historyStatus').textContent='Загружаем…';try{const data=await request(url(event,provider,more?next:''));if(!active()||token!==generation)return;entries=more?[...entries,...data.entries]:data.entries;next=data.nextCursor;$('historyEntries').innerHTML=rows(entries);$('historyMore').hidden=!next;$('historyStatus').textContent=entries.length?`${entries.length} изменений · последние первыми`:'История изменений пока не записана.';}catch(e){if(active()&&token===generation)$('historyStatus').textContent='Не удалось загрузить историю: '+e.message;}finally{if(active()&&token===generation){loading=false;$('historyMore').disabled=false;}}}
  $('historyFilters').onclick=e=>{const b=e.target.closest('[data-history-provider]');if(!b)return;provider=b.dataset.historyProvider;for(const el of $('historyFilters').querySelectorAll('[data-history-provider]'))el.setAttribute('aria-pressed',el===b);load();};
  $('historyMore').onclick=()=>{if(!loading&&next)load(true);};$('historyRefresh').onclick=()=>load();const autoRefresh=setInterval(()=>{if(active()&&!loading&&!browsingOlder)load();},5000);load();
 }
 const api={open,rows,url};if(typeof module==='object'&&module.exports)module.exports=api;else root.MatchHistory=api;
})(typeof globalThis!=='undefined'?globalThis:this);
