'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),BASE=ServerConfig.base,params=new URLSearchParams(location.search);
const dateFmt=new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}),date=at=>at?dateFmt.format(at):'нет даты',percent=p=>(p*100).toFixed(1)+'%',odd=v=>v==null?'—':v>=1000?v.toFixed(0):v.toFixed(3),fairOdd=v=>v==null?'—':settings?.maxOdds&&v>settings.maxOdds?odd(settings.maxOdds)+'+':odd(v);
let localData={teams:[],players:[],matches:[]},serverData={},data={},picks=[null,null],result=null,category='match',running=false,sourceStatus={},picker=null,searchSequence=0,jobId=null,settings={margin:7.5,bestOf:3,maxOdds:25},dirty=false;
const targets=[params.get('team1')||'',params.get('team2')||''];
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error);}
async function api(path,body){const r=await fetch(BASE+path,{method:body?'POST':'GET',headers:ServerConfig.headers(body?{'Content-Type':'application/json'}:{}),body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||(r.status===404?'Нужный API расчёта недоступен на сервере (HTTP 404)':'HTTP '+r.status));return d;}
function mergeData(){data=HltvData.merge(serverData,localData);data.players=data.players.map(p=>HltvData.derivePlayer(p));}
function teamFor(p){return p&&!p.custom?data.teams?.find(t=>t.id===p.id):null;}
function playersFor(p){return Array.from({length:5},(_,i)=>data.players?.find(x=>x.id===p?.playerIds?.[i]));}
function labelFor(p,side){return p?.custom?p.name:teamFor(p)?.name||targets[side]||'Команда '+(side+1);}
function markDirty(){dirty=true;if(result)status('Параметры изменились. Нажмите «Сгенерировать», чтобы получить новый расчёт.');}
function renderPicks(){
 $('teamPickers').innerHTML=picks.map((p,i)=>{const t=teamFor(p),ps=playersFor(p);return `<section class="team-pick"><div class="pick-heading"><div><h3>${esc(labelFor(p,i))}</h3><small>${p?.custom?'Состав из игроков HLTV':t?.at?'HLTV #'+t.id+' · '+date(t.at):'Выберите профиль HLTV'}</small></div><b>${i+1}</b></div>${p?.custom?`<input class="custom-name" data-custom-name="${i}" aria-label="Название состава ${i+1}" value="${esc(p.name)}" maxlength="120">`:''}<div class="pick-actions"><button data-pick-team="${i}">${p?'Изменить команду':'Выбрать команду'}</button><button data-custom="${i}">Свой состав</button>${t?`<button data-refresh-team="${i}">Обновить HLTV</button>`:''}</div><div class="roster">${Array.from({length:5},(_,j)=>{const player=ps[j];return `<button data-player-side="${i}" data-player-slot="${j}" class="${player?'':'missing'}" ${!p?'disabled':''}>${esc(player?.name||'Игрок '+(j+1))}</button>`;}).join('')}</div></section>`;}).join('');
 $('generate').disabled=running||!$('manualMode').checked&&picks.some(p=>!p||p.playerIds?.length!==5||!Array.from({length:5},(_,i)=>p.playerIds[i]).every(Boolean));renderMaps();
}
function renderMaps(){const previous=[...$('mapControls').querySelectorAll('select')].map(s=>s.value),pool=[...new Set((data.teams||[]).filter(t=>picks.some(p=>p?.id===t.id||p?.custom&&t.players?.some(x=>p.playerIds.includes(x.id)))).flatMap(t=>t.maps||[]).map(m=>m.name))].sort();$('mapControls').innerHTML=Array.from({length:Number($('bestOf').value)},(_,i)=>`<label>Карта ${i+1}<select data-map="${i}" aria-label="Карта ${i+1}"><option value="">Авто</option>${pool.map(m=>`<option ${previous[i]===m?'selected':''}>${esc(m)}</option>`).join('')}</select></label>`).join('');$('mapControls').querySelectorAll('select').forEach(s=>s.onchange=markDirty);}
function localCandidates(q,kind){const key=HltvData.norm(q);return (data[kind==='team'?'teams':'players']||[]).filter(t=>!key||HltvData.norm(t.name).includes(key)).sort((a,b)=>Number(!!b.at)-Number(!!a.at)||a.name.localeCompare(b.name)).slice(0,40);}
function renderPicker(q){const list=localCandidates(q,picker.kind);$('pickerResults').innerHTML=list.map(p=>`<button type="button" data-select-id="${p.id}"><span>${esc(p.name)}<small> · HLTV ${p.id}</small></span><small>${picker.kind==='team'?(p.at?'Профиль · '+date(p.at):'Нужна загрузка профиля'):(p.kpr?'Есть статистика убийств':p.rating?'Rating '+p.rating:'Нужна статистика')}</small></button>`).join('')||'<p class="hint">Нет совпадений в доступных данных. Можно импортировать HAR или указать ссылку HLTV.</p>';}
function openPicker(kind,side,slot){picker={kind,side,slot};searchSequence++;$('pickerTitle').textContent=kind==='team'?'Выберите команду HLTV':'Выберите игрока HLTV';$('pickerSearch').value='';$('pickerStatus').textContent='Поиск по имени, ID или ссылке HLTV';renderPicker('');$('pickerDialog').showModal();$('pickerSearch').focus();}
async function lookup(){const q=$('pickerSearch').value.trim(),sequence=++searchSequence;renderPicker(q);if(q.length<2)return;const match=q.match(new RegExp('/'+(picker.kind==='team'?'team':'(?:player|stats/players)')+'/(\\d+)'))||q.match(/^(\d+)$/);
 $('pickerStatus').textContent='Ищем в HLTV…';try{
  if(match){const d=await api('/api/hltv/'+picker.kind+'?id='+Number(match[1]));serverData=HltvData.merge(serverData,d.data);if(d.player)serverData=HltvData.merge(serverData,{players:[d.player]});}
  else{const d=await api('/api/hltv/search?q='+encodeURIComponent(q));serverData=HltvData.merge(serverData,d);sourceStatus=d.status||sourceStatus;}
  mergeData();if(sequence!==searchSequence||!$('pickerDialog').open)return;renderPicker(match?'':q);$('pickerStatus').textContent=sourceStatus.lastError||'Выберите нужный профиль. Совпадение по имени не всегда однозначно.';
 }catch(e){if(sequence===searchSequence)$('pickerStatus').textContent=e.message;}
}
async function selectTeam(side,id){let t=data.teams?.find(t=>t.id===id);if(!t?.at||t.players?.length!==5){const d=await api('/api/hltv/team?id='+id);serverData=HltvData.merge(serverData,d.data);mergeData();t=data.teams.find(t=>t.id===id);sourceStatus=d.status||sourceStatus;}if(!t?.at)throw Error('Импортируйте страницу этой команды HLTV');picks[side]={id,playerIds:t.players.map(p=>p.id)};markDirty();renderPicks();}
$('pickerSearch').oninput=()=>{clearTimeout(lookup.timer);lookup.timer=setTimeout(lookup,450);};
$('pickerResults').onclick=async e=>{const b=e.target.closest('[data-select-id]');if(!b)return;const id=Number(b.dataset.selectId),pick={...picker};b.disabled=true;try{if(pick.kind==='team')await selectTeam(pick.side,id);else{let p=data.players.find(p=>p.id===id);if(!p?.rating&&!p?.kpr){const d=await api('/api/hltv/player?id='+id);serverData=HltvData.merge(serverData,d.data,{players:[d.player]});mergeData();p=data.players.find(p=>p.id===id);}if(!p)throw Error('Нет статистики игрока');picks[pick.side].playerIds[pick.slot]=id;markDirty();renderPicks();}$('pickerDialog').close();}catch(err){$('pickerStatus').textContent=err.message;}finally{b.disabled=false;}};
$('teamPickers').onclick=async e=>{const team=e.target.closest('[data-pick-team]');if(team){openPicker('team',Number(team.dataset.pickTeam));return;}const custom=e.target.closest('[data-custom]');if(custom){const i=Number(custom.dataset.custom);picks[i]={custom:true,name:'Состав '+(i+1),playerIds:[...(picks[i]?.playerIds||[])]};markDirty();renderPicks();return;}const player=e.target.closest('[data-player-side]');if(player){openPicker('player',Number(player.dataset.playerSide),Number(player.dataset.playerSlot));return;}const refresh=e.target.closest('[data-refresh-team]');if(refresh){refresh.disabled=true;status('Обновляем профиль HLTV…');try{const d=await api('/api/hltv/team?id='+picks[Number(refresh.dataset.refreshTeam)].id+'&refresh=1');serverData=HltvData.merge(serverData,d.data);mergeData();markDirty();renderPicks();status(d.status?.lastError||'Профиль обновлён',!!d.status?.lastError);}catch(err){status(err.message,true);}finally{refresh.disabled=false;}}};
$('teamPickers').oninput=e=>{if(e.target.dataset.customName!==undefined){picks[Number(e.target.dataset.customName)].name=e.target.value;markDirty();}};
$('bestOf').onchange=()=>{if($('manualMode').checked)renderManualMaps();settings.bestOf=Number($('bestOf').value);chrome.storage.local.set({oddsSettings:settings});markDirty();renderMaps();};
function repriceResult(){if(!result)return;result.margin=settings.margin;result.maxOdds=settings.maxOdds;for(const c of result.categories)for(const m of c.markets)if(m.available)m.outcomes=OddsPricing.price(m.outcomes,settings.margin,settings.maxOdds);renderHeadlines();renderMarkets();}
function setMargin(input){if(!input.value.trim())return;const margin=Number(input.value);if(!Number.isFinite(margin)||margin<0||margin>25){status('Маржа должна быть от 0 до 25%',true);return;}$('margin').value=margin;$('resultMargin').value=margin;settings.margin=margin;chrome.storage.local.set({oddsSettings:settings});repriceResult();}
function setMaxOdds(input){if(!input.value.trim())return;const maxOdds=Number(input.value);if(!Number.isFinite(maxOdds)||maxOdds<1.01||maxOdds>10000){status('Максимальный коэффициент должен быть от 1.01 до 10000',true);return;}$('maxOdds').value=maxOdds;$('resultMaxOdds').value=maxOdds;settings.maxOdds=maxOdds;chrome.storage.local.set({oddsSettings:settings});repriceResult();}
$('margin').oninput=e=>setMargin(e.target);$('resultMargin').oninput=e=>setMargin(e.target);$('maxOdds').oninput=e=>setMaxOdds(e.target);$('resultMaxOdds').oninput=e=>setMaxOdds(e.target);
function renderHeadlines(){const m=result.categories[0].markets[0];$('headlineOdds').innerHTML=m.outcomes.map(o=>`<div class="outcome-headline"><span><strong>${esc(o.label)}</strong><small>Вероятность ${percent(o.probability)} · без маржи ${fairOdd(o.fairOdds)}</small></span><b>${odd(o.odds)}</b></div>`).join('');}
function matchesMarket(m,q){return !q||HltvData.norm(m.title+' '+(m.outcomes||[]).map(o=>o.label).join(' ')).includes(q);}
const marketGroups=new Map();let allGroupsOpen=true;
function groupName(m){const t=m.title.toLowerCase();return /пистолет/.test(t)?'Пистолетные':/половин/.test(t)?'Половины':/убийств|хэдшот/.test(t)?'Игроки':/ и | \/ /.test(t)?'Комбинации':/точный счёт/.test(t)?'Точный счёт':/фора|разница/.test(t)?'Форы и разница':/тотал/.test(t)?'Тоталы':/гонка|раунда \d/.test(t)?'Раунды':/победитель|исход|выиграет/.test(t)?'Исходы':'Особые рынки';}
function groupedMarkets(c,markets,render){const groups=new Map();for(const m of markets){const name=groupName(m);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(m);}return [...groups].map(([name,rows])=>{const key=c.id+'|'+name,open=marketGroups.get(key)??allGroupsOpen;return '<details class="market-group" data-market-group="'+esc(key)+'" '+(open?'open':'')+'><summary>'+esc(name)+' <small>'+rows.length+'</small></summary>'+rows.map(render).join('')+'</details>';}).join('');}
$('markets').addEventListener('toggle',e=>{if(e.target.dataset.marketGroup)marketGroups.set(e.target.dataset.marketGroup,e.target.open);},true);
$('foldMarkets').onclick=()=>{allGroupsOpen=!allGroupsOpen;marketGroups.clear();$('foldMarkets').textContent=allGroupsOpen?'Свернуть группы':'Раскрыть группы';renderMarkets();};
function renderMarkets(){if(!result)return;const q=HltvData.norm($('marketSearch').value),available=$('availableOnly').checked;const include=m=>(!available||m.available)&&matchesMarket(m,q);let selected=result.categories.filter(c=>q||c.id===category),count=selected.reduce((s,c)=>s+c.markets.filter(include).length,0);
 $('categories').innerHTML=result.categories.map(c=>`<button data-category="${esc(c.id)}" aria-pressed="${category===c.id}">${esc(c.title)} · ${c.markets.filter(include).length}</button>`).join('');
 $('marketCount').textContent=count+' рынков';$('markets').innerHTML=selected.map(c=>{const markets=c.markets.filter(include);if(!markets.length)return '';const note=[c.condition,c.mapMix?.map(m=>m.name+' '+percent(m.probability)).join(' · ')].filter(Boolean).join('. ');return `${q?`<h2>${esc(c.title)}</h2>`:''}${note?`<p class="category-note">${esc(note)}</p>`:''}`+groupedMarkets(c,markets,m=>`<article class="market"><h3>${esc(m.title)}</h3>${m.condition||m.note?`<p class="market-note">${esc([m.condition,m.note].filter(Boolean).join(' · '))}${m.pushProbability!=null?' · Возврат '+percent(m.pushProbability):''}${m.reachProbability!=null?' · Будет сыгран '+percent(m.reachProbability):''}</p>`:''}${m.available?`<div class="outcomes">${m.outcomes.map(o=>`<div class="outcome"><span>${esc(o.label)}<small>${percent(o.probability)} · без маржи ${fairOdd(o.fairOdds)}</small></span><b>${odd(o.odds)}</b></div>`).join('')}</div>`:`<div class="not-available">${esc(m.reason)}</div>`}</article>`);}).join('')||'<p class="empty-markets">Нет рассчитанных рынков в этой категории. Отключите «Только рассчитанные», чтобы увидеть причины.</p>';
}
function renderEvidence(){const r=result;if(r.manual){$('evidenceBody').innerHTML='<p>Расчёт по введённым коэффициентам. HLTV не используется.</p><p>'+r.manual.names.map((n,i)=>esc(n)+' · '+percent(i===0?r.manual.probability:1-r.manual.probability)).join(' / ')+'</p><ul>'+r.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul>';return;}$('evidenceBody').innerHTML='<div class="evidence-grid">'+r.teams.map(t=>`<section><h3>${esc(t.name)}</h3><p class="hint">Данные профиля: ${date(t.at)}</p><dl><dt>Матчи в окне 180 дней</dt><dd>${t.factors.matches}</dd><dt>Карты в статистике профиля</dt><dd>${t.factors.mapCount?.toFixed(0)||0}</dd><dt>Игроки с Rating 3.0</dt><dd>${t.factors.rosterRated} / 5</dd><dt>Средний сглаженный Rating</dt><dd>${t.factors.rosterRating?.toFixed(3)||'нет данных'}</dd><dt>Ранг HLTV (справочно)</dt><dd>${t.rank||'—'}</dd></dl><p>${(t.players||[]).map(p=>`${esc(p.name)}${p.rating?' · Rating '+esc(p.ratingVersion||'')+' '+p.rating.toFixed(2)+(p.ratingPeriod==='team tenure'?' (в команде)':p.ratingPeriod==='past 3 months'?' (3 месяца)':''):''}${p.kpr?' · KPR '+p.kpr.toFixed(2):''}${p.statsPeriod==='all time'?' (карьера)':p.observedMaps?' ('+p.observedMaps+' карт · '+esc(p.startDate)+' – '+esc(p.endDate)+')':''}${p.dispersionMaps?' · разброс убийств по '+p.dispersionMaps+' картам':''}${p.headshotPeriod==='all time'?' · HS за карьеру':''}`).join('<br>')}</p></section>`).join('')+'</div><h3>Метод</h3><ul>'+r.methods.map(m=>'<li>'+esc(m)+'</li>').join('')+'</ul><h3>Проверка</h3><p>'+esc(r.validation.message)+'</p>'+(r.validation.brier!=null?`<p>Тест: ${r.validation.test} матчей · Brier ${r.validation.brier.toFixed(3)} · Log loss ${r.validation.logLoss.toFixed(3)}</p>`:'')+'<h3>Ограничения данных</h3><ul>'+r.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul><p>Вероятности карт и связанных рынков рассчитаны по '+r.samples.toLocaleString('ru-RU')+' симуляциям. Цены округлены до трёх знаков; фактическая маржа округлённых цен может слегка отличаться.</p><details><summary>Источники данных</summary><ul>'+r.sources.filter(s=>/^https:\/\/www\.hltv\.org\//.test(s)).map(s=>`<li><a href="${esc(s)}" target="_blank" rel="noreferrer">${esc(s)}</a></li>`).join('')+'</ul></details>';}
function showResult(value){const note=document.querySelector('.model-note');if(note)note.textContent=value.manual?'Расчёт от введённых цен. Исходы карт предполагаются независимыми; рынки раундов — приближение MR12/MR3, а не прогноз HLTV.':'Оценки экспериментальной модели. Точность полной модели пока не подтверждена.';result=value;dirty=false;category='match';marketGroups.clear();allGroupsOpen=true;$('foldMarkets').textContent='Свернуть группы';$('results').hidden=false;$('resultTitle').textContent=result.teams.map(t=>t.name).join(' - ');$('pairTitle').textContent=$('resultTitle').textContent;$('resultMeta').textContent='Bo'+result.bestOf+' · '+date(result.generatedAt)+' · '+result.samples.toLocaleString('ru-RU')+' симуляций';repriceResult();renderEvidence();$('setup').open=false;status('Расчёт готов. Данные и допущения доступны под списком рынков.');}
async function generate(){if($('manualMode').checked)return generateManual();if(running)return;const margin=Number($('margin').value),maxOdds=Number($('maxOdds').value);if(!$('margin').value.trim()||!Number.isFinite(margin)||margin<0||margin>25){status('Укажите маржу от 0 до 25%',true);return;}if(!$('maxOdds').value.trim()||!Number.isFinite(maxOdds)||maxOdds<1.01||maxOdds>10000){status('Укажите максимальный коэффициент от 1.01 до 10000',true);return;}if(picks.some(p=>!p||p.playerIds.length!==5||!Array.from({length:5},(_,i)=>p.playerIds[i]).every(Boolean))){status('Выберите две команды с пятью игроками',true);return;}running=true;$('setup').querySelectorAll('button,select,input').forEach(x=>{if(x.id!=='margin')x.disabled=true;});$('generate').disabled=true;$('progressBox').hidden=false;$('progress').value=0;$('progressText').textContent='Подготовка статистики HLTV…';status('Расчёт выполняется на сервере…');try{const job=await api('/api/odds/generate',{teams:picks,bestOf:Number($('bestOf').value),margin,maxOdds,roundVolatility:.38,maps:[...$('mapControls').querySelectorAll('select')].map(s=>s.value),data:localData});jobId=job.id;const deadline=Date.now()+180000;for(;;){if(Date.now()>deadline)throw Error('Сервер не завершил расчёт вовремя. Попробуйте ещё раз.');await new Promise(r=>setTimeout(r,700));const j=await api('/api/odds/job?id='+encodeURIComponent(jobId));$('progress').value=j.progress;$('progressText').textContent=(j.progress<10?'Загружаем доступную статистику HLTV':'Считаем вероятности и рынки')+' · '+j.progress+'%';if(j.status==='error')throw Error(j.error);if(j.status==='done'){showResult(j.result);break;}}}catch(error){status(error.message,true);$('setup').open=true;}finally{running=false;$('progressBox').hidden=true;$('setup').querySelectorAll('button,select,input').forEach(x=>x.disabled=false);renderPicks();}}
$('generate').onclick=generate;$('categories').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;$('marketSearch').value='';renderMarkets();}};$('marketSearch').oninput=renderMarkets;$('availableOnly').onchange=renderMarkets;
$('closeWindow').onclick=()=>window.close();$('pickerDialog').onclick=e=>{if(e.target!==$('pickerDialog'))return;const r=$('pickerDialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('pickerDialog').close();};
$('importHar').onclick=()=>$('harFile').click();
$('harFile').onchange=async()=>{
 const file=$('harFile').files[0];if(!file||running)return;
 if(file.size>1073741824){status('HAR больше 1 ГБ (1024 МБ).',true);$('harFile').value='';return;}
 running=true;const disabled=[...$('setup').querySelectorAll('button,select,input')].map(x=>[x,x.disabled]);disabled.forEach(([x])=>x.disabled=true);
 $('cancelHar').hidden=false;$('cancelHar').disabled=false;$('progressBox').hidden=false;$('progress').value=0;
 $('progressText').textContent='Читаем HAR…';status('Разбираем страницы HLTV из HAR…');let worker;
 try{
  worker=new Worker('hltv-import-worker.js');
  const parsed=await new Promise((resolve,reject)=>{
   $('cancelHar').onclick=()=>{worker.terminate();reject(Error('Импорт отменён. Сохранённая база не изменилась.'));};
   worker.onmessage=({data:message})=>{if(message.progress!=null){$('progress').value=message.progress;$('progressText').textContent='Импорт HAR · '+message.progress+'% · страниц HLTV: '+message.pages;return;}if(message.error)reject(Error(message.error));else resolve(message.data);};
   worker.onerror=()=>reject(Error('Не удалось прочитать HAR'));worker.postMessage({file});
  });
  $('cancelHar').disabled=true;const next=HltvData.merge(localData,parsed);await chrome.storage.local.set({hltvLocalData:next});localData=next;
  mergeData();renderPicks();markDirty();await autoPick(false);
  const mapCount=parsed.players.reduce((n,p)=>n+(p.mapHistory?.length||0),0);
  status('Импортировано страниц: '+parsed.pages+'. Команд: '+parsed.teams.length+'. Игроков: '+parsed.players.length+'. Записей карт игроков: '+mapCount+'.'+(parsed.skipped||parsed.oversized?' Пропущено: '+(parsed.skipped+parsed.oversized)+' записей (неподдерживаемое содержимое или слишком большая отдельная запись).':'')+' Статистика сохранена.');
 }catch(e){status(e.message,true);}
 finally{worker?.terminate();running=false;$('harFile').value='';$('cancelHar').hidden=true;$('cancelHar').onclick=null;$('progressBox').hidden=true;disabled.forEach(([x,value])=>x.disabled=value);renderPicks();}
};
$('exportJson').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='CS2-odds-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
async function autoPick(remote=true){for(let i=0;i<2;i++){if(picks[i]||!targets[i])continue;const key=HltvData.norm(targets[i]);let found=localCandidates(targets[i],'team').filter(t=>HltvData.norm(t.name)===key&&t.at);if(!found.length&&remote){try{const d=await api('/api/hltv/search?q='+encodeURIComponent(targets[i]));serverData=HltvData.merge(serverData,d);mergeData();found=localCandidates(targets[i],'team').filter(t=>HltvData.norm(t.name)===key);}catch{}}if(found.length===1){try{await selectTeam(i,found[0].id);}catch(e){status(e.message,true);}}}renderPicks();}
async function boot(){
 const saved=await chrome.storage.local.get(['prefs','oddsSettings','hltvLocalData']);localData=saved.hltvLocalData||localData;settings={...settings,...saved.oddsSettings};document.documentElement.dataset.theme=saved.prefs?.theme==='system'||!saved.prefs?.theme?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):saved.prefs.theme;$('margin').value=settings.margin;$('resultMargin').value=settings.margin;$('maxOdds').value=settings.maxOdds;$('resultMaxOdds').value=settings.maxOdds;$('bestOf').value=[1,3,5].includes(Number(params.get('bo')))?params.get('bo'):settings.bestOf;mergeData();renderPicks();
 if($('manualMode').checked){initManual();status('Введите исходные коэффициенты. Расчёт выполняется в расширении.');return;}
 try{const d=await api('/api/hltv/data');serverData=d.data;sourceStatus=d.status;mergeData();status('Доступно профилей команд: '+data.teams.filter(t=>t.at).length+'. Данные можно дополнить импортом HAR.');}catch(e){status(e.message,true);}
 await autoPick();if(params.get('auto')==='1'&&picks.every(Boolean))generate();
}
