'use strict';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),ids=params.get('ids')||'',base={team1:params.get('team1')||'',team2:params.get('team2')||''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=new Intl.DateTimeFormat('ru-RU',{timeZone:'Asia/Yerevan',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'});
let entries=[],provider='all',running=false,nextBefore=null,initialized=false;
$('matchName').textContent=base.team1+' - '+base.team2;
chrome.storage.local.get('prefs').then(({prefs={}})=>{document.documentElement.dataset.theme=prefs.theme==='system'||!prefs.theme?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):prefs.theme;});
try{const current=JSON.parse(params.get('current')||'[]');$('currentScore').textContent='Текущий снимок: '+current.map(r=>(r.source==='astek'?'AstekBet':'Fonbet')+' '+(ScoreOrientation.orient(r,base).scoreText||'—')).join(' · ');}catch{}
function render(){const rows=ScoreTimeline.build(entries,base).filter(r=>provider==='all'||r.changed.includes(provider));$('count').textContent=rows.length+' изменений';$('more').hidden=!nextBefore;$('entries').innerHTML='<table class="score-table"><thead><tr><th>Время</th><th>AstekBet</th><th>Fonbet</th></tr></thead><tbody>'+rows.map(row=>'<tr><td>'+esc(fmt.format(row.at))+'</td>'+['astek','fonbet'].map(source=>'<td class="'+(row.changed.includes(source)?'score-updated':'score-previous')+'">'+esc(row.scores[source]?.scoreText||'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function accept(data,older=false){entries=[...new Map([...entries,...(data.entries||[])].map(r=>[[r.key,r.source,r.at,r.scoreText].join('|'),r])).values()];if(older||!initialized)nextBefore=data.hasMore?data.nextBefore:null;initialized=true;render();}
async function refresh(older=false){if(running)return;running=true;$('refresh').disabled=true;$('more').disabled=true;try{const data=await ScoreCache.load(ids,older&&nextBefore?{before:nextBefore}:{});accept(data,older);$('status').textContent=entries.length?'Обновлено '+fmt.format(Date.now())+' · Новые изменения сверху':'Записей пока нет. Журнал начинается после обновления сервера.';}catch(error){$('status').textContent=error.message;}finally{running=false;$('refresh').disabled=false;$('more').disabled=false;}}
document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{provider=b.dataset.provider;document.querySelectorAll('[data-provider]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();});
$('more').onclick=()=>refresh(true);$('refresh').onclick=()=>refresh();render();ScoreCache.read(ids).then(data=>{if(data&&Date.now()-data.cachedAt<30000&&!entries.length){accept(data);$('status').textContent='Сохранённый журнал · обновляем…';}}).catch(()=>{});refresh();setInterval(()=>refresh(),5000);
