import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {generateOdds,roundMapProbability,seriesProbability,fitRatings} from '../src/odds-model.js';
import {HltvService,safeDataset} from '../src/hltv-service.js';
import {OddsService} from '../src/odds-service.js';
import Pricing from '../src/odds-pricing.cjs';
import HltvData from '../src/hltv-data.cjs';
const now=Date.now(),seed=JSON.parse(fs.readFileSync(new URL('../src/hltv-seed.json',import.meta.url))),data=safeDataset(seed),pick=(id)=>{const t=data.teams.find(t=>t.id===id);return {...t,players:t.players.map(p=>({...p,...data.players.find(x=>x.id===p.id)}))};},near=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const symmetric=()=>[1,2].map(id=>({id,name:'Team '+id,at:now,players:Array.from({length:5},(_,i)=>({id:id*100+i,name:'p'+id+i,rating:1,ratingVersion:'3.0',maps:40,at:now})),maps:['A','B','C','D','E','F','G'].map(name=>({name,wins:10,losses:10,played:20,pistol:.5,pick:.2,ban:.2}))}));
test('power margin is exact, supports zero, multiway and heavy favourites',()=>{for(const ps of [[.5,.5],[.9999,.0001],[.7,.2,.1],[.8,.2,0]])for(const margin of [0,7.5,25]){const out=Pricing.price(ps.map(probability=>({probability})),margin);near(out.reduce((s,o)=>s+(o.odds?1/o.odds:0),0),1+margin/100);assert.ok(out.every(o=>o.odds===null||o.odds>1));out.forEach((x,i)=>near(x.probability,ps[i]));}assert.throws(()=>Pricing.price([{probability:.5},{probability:.5}],-1));assert.throws(()=>Pricing.price([{probability:NaN}],7.5));assert.equal(Pricing.price([{probability:1},{probability:0}],7.5)[0].odds,null);});
test('MR12 + repeated overtime has symmetry and Bo format amplification',()=>{near(roundMapProbability(.5),.5);for(const q of [.35,.45,.55,.65])near(roundMapProbability(q,.54)+roundMapProbability(1-q,.46),1);assert.ok(roundMapProbability(.6)>.8);near(seriesProbability(.5,5),.5);assert.ok(seriesProbability(.7,5)>seriesProbability(.7,3));});
test('historical model excludes future observations and learns opponent-adjusted wins',()=>{const rows=Array.from({length:12},(_,i)=>({id:i,at:now-86400100-i,teamA:1,teamB:2,scoreA:2,scoreB:0}));const fit=fitRatings(rows,now),future=fitRatings([...rows,{...rows[0],id:30,at:now+1,scoreA:0,scoreB:2}],now);assert.ok(fit.ratings.get(1).mu>fit.ratings.get(2).mu);near(fit.ratings.get(1).mu,future.ratings.get(1).mu);assert.equal(fit.count,12);});
test('markets share one outcome distribution, conditional maps, overround and totals monotonicity',()=>{
 const r=generateOdds({matches:[]},{teams:symmetric(),bestOf:3,samples:10000,seed:888,now});const get=(c,title)=>r.categories.find(x=>x.id===c).markets.find(m=>m.title===title),p=(m,label)=>m.outcomes.find(o=>o.label===label).probability;
 const winner=get('match','Победитель матча'),scores=get('match','Точный счёт по картам');near(winner.outcomes[0].probability,.5,.035);near(winner.outcomes[0].probability,p(scores,'2:0')+p(scores,'2:1'));
 const h=r.categories[0].markets.find(m=>m.title==='Фора по картам'&&m.line===-1.5);near(h.outcomes[0].probability,p(scores,'2:0'));const t=get('match','Тотал карт');near(t.outcomes[1].probability,p(scores,'2:1')+p(scores,'1:2'));
 const m3=get('map-3','Победитель карты, включая ОТ');near(m3.sampleCount/r.samples,t.outcomes[1].probability);near(m3.outcomes[0].probability,p(scores,'2:1')/(p(scores,'2:1')+p(scores,'1:2')));
 for(const c of r.categories)for(const m of c.markets)if(m.available){near(m.outcomes.reduce((s,x)=>s+x.probability,0),1);if(m.outcomes.filter(x=>x.probability>0).length>1)near(m.outcomes.reduce((s,x)=>s+(x.odds?1/x.odds:0),0),1.075);assert.ok(m.outcomes.every(x=>x.odds==null||Number.isFinite(x.odds)&&x.odds>1));}
 const totals=r.categories.find(c=>c.id==='map-1').markets.filter(m=>m.title==='Тотал раундов на карте, включая ОТ');for(let i=1;i<totals.length;i++)assert.ok(totals[i].outcomes[1].probability<=totals[i-1].outcomes[1].probability);
 assert.equal(get('map-1','Будет убийство ножом').available,false);assert.equal(r.validation.status,'insufficient');
});
test('HAR-derived profiles preserve map sample sizes, players, match IDs and provenance',()=>{const t=data.teams.find(t=>t.id===6667);assert.equal(t.name,'FaZe');assert.equal(t.players.length,5);assert.equal(t.maps.find(m=>m.name==='Cache').wins,6);assert.equal(t.maps.find(m=>m.name==='Cache').played,8);assert.ok(data.matches.length>=40);assert.ok(!JSON.stringify(data).includes('cookie'));assert.equal(data.players.find(p=>p.id===8711).statsPeriod,'all time');});
test('input validation refuses absent data, invalid maps and duplicate rosters',()=>{const teams=symmetric();assert.throws(()=>generateOdds(data,{teams,bestOf:2}),/Bo1/);assert.throws(()=>generateOdds(data,{teams,bestOf:3,maps:['A','A','B']}),/разные карты/);assert.throws(()=>generateOdds(data,{teams:[teams[0],teams[0]]}),/разные команды/);assert.throws(()=>generateOdds(data,{teams:[{id:99,name:'Unknown',players:[],maps:[]},teams[0]]}),/Недостаточно статистики/);const b={...teams[1],players:[teams[0].players[0],...teams[1].players.slice(1)]};assert.throws(()=>generateOdds(data,{teams:[teams[0],b]}),/Один игрок/);});
test('HLTV 403 uses cache and backoff without cookies or repeated upstream attempts',async()=>{let requests=0;const service=new HltvService({read:async()=>({}),write:async()=>{},gap:0,request:async(url,options)=>{requests++;assert.equal(options.headers.Cookie,undefined);return new Response('',{status:403});}});await service.ready;const first=await service.search('FaZe');assert.ok(first.teams.some(t=>t.id===6667));assert.match(first.status.lastError,/403/);await service.search('NRG');assert.equal(requests,1);assert.ok(service.blockedUntil>Date.now());const prepared=await service.prepare({teams:[{id:9565},{id:6667}]});assert.equal(prepared.options.teams.length,2);assert.equal(requests,1);});
test('custom rosters inherit known map exposure and do not modify shared data',async()=>{const service=new HltvService({read:async()=>({}),write:async()=>{}});await service.ready;service.blockedUntil=Date.now()+60000;const old=JSON.stringify(service.data),a=pick(9565),b=pick(6667);const prepared=await service.prepare({teams:[{custom:true,name:'Custom A',playerIds:a.players.map(p=>p.id)},{custom:true,name:'Custom B',playerIds:b.players.map(p=>p.id)}]});assert.equal(prepared.options.teams[0].maps.length,a.maps.length);assert.equal(prepared.options.teams[0].rosterOverlap,0);assert.equal(JSON.stringify(service.data),old);});
test('worker jobs complete while event loop remains responsive and errors are surfaced',async()=>{const h=new HltvService({read:async()=>({}),write:async()=>{}});await h.ready;h.blockedUntil=Date.now()+60000;const service=new OddsService(h);let ticks=0;const timer=setInterval(()=>ticks++,10);try{const job=service.create({teams:[{id:9565},{id:6667}],bestOf:3,margin:7.5});const deadline=Date.now()+15000;let done;while(Date.now()<deadline){done=service.get(job.id);if(['done','error'].includes(done.status))break;await new Promise(r=>setTimeout(r,20));}assert.equal(done.status,'done',done.error);assert.ok(ticks>5);assert.ok(done.result.categories.length>=8);assert.equal(done.body,undefined);assert.equal(service.get('missing'),null);}finally{clearInterval(timer);await service.stop();}});
