// Whitelisted application data only. Private attachments are never serialized by API/SSE.
export function historyPrice(price, rawOdds, format='decimal') {
  Object.defineProperty(price,'__historyRaw',{value:{rawOdds,format},enumerable:false});return price;
}
export function historyEventMeta(event, meta) {Object.defineProperty(event,'__historyMeta',{value:meta,enumerable:false});return event;}
const iso=value=>{const n=typeof value==='number'?value:Date.parse(value);return Number.isFinite(n)&&n>0?new Date(n).toISOString():null;};
export function projectEvent(provider,event,context={}) {
  const gg=provider.startsWith('ggbet-'),fixture=event.fixture||{},meta=event.__historyMeta||{},pairs=Object.fromEntries((gg?(event.meta||[]):[]).filter?.(x=>x&&typeof x==='object').map(x=>[x.name,x.value])||[]);
  const eventId=String(gg?event.id:(event.sourceEventId||event.id)||'');if(!eventId)return null;
  const state={eventVersion:gg?event.version??null:meta.eventVersion??context.eventVersion??event.eventVersion??null,sport:gg?fixture.sportId??null:event.category??event.sportName??null,eventName:gg?fixture.title??null:[event.team1,event.team2].filter(Boolean).join(' vs '),score:meta.score??(gg?fixture.score??null:event.scoreText??null),seriesScore:meta.seriesScore??event.seriesScore??null,mapScores:meta.mapScores??event.mapScores??null,providerState:meta.providerState??null,competitorScores:gg?(fixture.competitors||[]).map(c=>({id:c.id,homeAway:c.homeAway,score:[...(c.score||[])].sort((a,b)=>String(a.id).localeCompare(String(b.id)))})).sort((a,b)=>String(a.id).localeCompare(String(b.id))):null,map:meta.map??pairs.map??event.currentMap??null,period:meta.period??event.period??null,clock:meta.clock??pairs.time??event.clock??null,gameState:meta.gameState??fixture.status??event.status??null,betStop:gg?event.betStop??null:meta.betStop??event.betStop??null};
  const markets=(gg?event.markets:meta.markets??event.odds?.markets)||[];
  return {provider,eventId,state,source:provider==='ggbet-browser'?'browser':'node',phase:context.phase??event.odds?.mode??'live',sourceReceivedAt:iso(provider==='ggbet-node'?event.__sourceReceivedAt??event.__receivedAt??context.sourceReceivedAt:context.sourceReceivedAt),receivedTimeSemantics:context.receivedTimeSemantics||'collector-application-receive',updatedAt:iso(gg?context.updatedAt??event.__updatedAt: event.odds?.updatedAt??event.updatedAt),providerTimestamp:iso(meta.providerTimestamp??event.providerTimestamp),session:context.session??null,authority:context.authority??(provider==='ggbet-browser'?'browser-authoritative':'collector-observed'),markets:markets.map(m=>{const specs=Array.isArray(m.specifiers)?Object.fromEntries(m.specifiers.map(s=>[s.name,s.value])):(m.specifiers||{});return {marketId:String(m.id??m.key??[m.period,m.rawGroup,m.type].join('|')),typeId:m.typeId??m.rawType??m.rawGroup??m.type??null,marketName:m.name??m.title??m.type??null,marketStatus:m.status??null,marketVersion:m.version??null,period:m.period??specs.period??null,map:specs.mapnr??specs.map??null,line:specs.total??specs.handicap??specs.line??null,specifiers:specs,outcomes:(gg?m.odds||[]:m.prices||[]).map((o,i)=>({outcomeId:String(o.id??o.rawType??o.designation??o.participantId??i),identityKind:o.id!=null?'provider-id':'provider-factor-or-derived-position',outcomeName:o.name??o.label??o.designation??null,rawOdds:gg?o.value:o.__historyRaw?.rawOdds??o.price??o.decimal??null,oddsFormat:gg?'decimal':o.__historyRaw?.format??(o.price!=null?'american':'decimal'),decimalOdds:gg?o.value:o.__historyRaw?.format==='decimal'?o.__historyRaw.rawOdds:o.decimal??null,isActive:gg?o.isActive??null:o.isActive??(m.status==='open'&&o.decimal!=null),line:o.points??null}))};})};
}
