// Reuse captured observations; migration and initial baselines are excluded from steady-state growth.
import fs from 'node:fs';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {performance} from 'node:perf_hooks';
import {SqliteHistoryStore} from '../server/src/sqlite-history-store.js';import {eventHistoryQuery} from '../server/src/match-history-query.js';
const dir=process.argv[2];if(!dir||!path.resolve(dir).startsWith('/root/sqlite-history-implementation/'))throw Error('Isolated directory required');
const rows=fs.readFileSync(path.join(dir,'observations.ndjson'),'utf8').trim().split('\n').map(x=>JSON.parse(x));const db=new DatabaseSync(path.join(dir,'monitor-v2.sqlite3'));db.exec('PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;');let clock=rows[0].capturedAt;const store=new SqliteHistoryStore(db,{now:()=>clock}),keys=new Set();
const size=()=>({db:fs.statSync(path.join(dir,'monitor-v2.sqlite3')).size,wal:fs.existsSync(path.join(dir,'monitor-v2.sqlite3-wal'))?fs.statSync(path.join(dir,'monitor-v2.sqlite3-wal')).size:0});
const warmupEnd=rows[0].capturedAt+20000;let baseline,before,cpu,startWall,startAt,last=0,peakWal=0;
for(const row of rows){if(last&&last!==row.capturedAt){store.flush();peakWal=Math.max(peakWal,size().wal);}if(!baseline&&row.capturedAt>=warmupEnd){store.flush();db.exec('PRAGMA wal_checkpoint(TRUNCATE)');baseline={...store.stats};before=size();cpu=process.cpuUsage();startWall=performance.now();startAt=row.capturedAt;peakWal=0;}last=row.capturedAt;clock=row.capturedAt;keys.add((row.event.provider.startsWith('ggbet')?'ggbet':row.event.provider)+':'+row.event.eventId.replace(/^\d+:/,''));store.observe(row.event);}
store.flush();peakWal=Math.max(peakWal,size().wal);const replayWallMs=performance.now()-startWall,cpuUsed=process.cpuUsage(cpu);db.exec('PRAGMA wal_checkpoint(TRUNCATE)');const after=size();const stats=Object.fromEntries(Object.entries(store.stats).map(([k,v])=>[k,typeof v==='number'?v-(baseline[k]||0):v]));const duration=(rows.at(-1).capturedAt-startAt)/1000,perDay=86400/duration,queries=[];
for(const key of [...keys].slice(0,100)){const t=performance.now();eventHistoryQuery([key],{limit:100},db);queries.push(performance.now()-t);}queries.sort((a,b)=>a-b);
const report={capturedWindow:{from:new Date(rows[0].capturedAt).toISOString(),to:new Date(rows.at(-1).capturedAt).toISOString()},warmupSeconds:20,steadySeconds:duration,baseline,steadyStats:stats,rowsPerDay:Math.round((stats.oddsRows+stats.scoreRows)*perDay),compressedOddsMiBPerDay:stats.compressedBytes/1048576*perDay,dbGrowthMiBPerDay:Math.max(0,after.db-before.db)/1048576*perDay,planningSevenDayGiB:Math.max(0,after.db-before.db)/1048576*perDay*3*7/1024,transactionsPerSecond:stats.transactions/duration,replayWallMs,replayCpuMs:(cpuUsed.user+cpuUsed.system)/1000,projectedCpuPercent:(cpuUsed.user+cpuUsed.system)/1000/(duration*1000)*100,walPeakMiB:peakWal/1048576,queryMs:{p50:queries[Math.floor(queries.length*.5)],p95:queries[Math.floor(queries.length*.95)],max:queries.at(-1)},before,after,limitations:['Two-minute local sampling can miss fast changes and quiet providers; threefold headroom is an assumption.','Source metadata absent from published snapshots can add rows in production.','No production database writes; migration/baseline growth excluded.']};fs.writeFileSync(path.join(dir,'steady-report.json'),JSON.stringify(report,null,2),{mode:0o600});console.log(JSON.stringify(report,null,2));db.close();
