// Builds the web app and the desktop app frontend from the shared UI (extension/, the approved 9.3.0 UI) plus the
// platform layer (web/platform/). No bundler, no minifier, no source maps: the files are the reviewed sources.
//
//   node web/build.mjs                 → dist/web    (served by the gateway at https://esportsdata.online)
//   node web/build.mjs --target tauri  → dist/tauri  (bundled into the desktop app; API at EDS_API_BASE)
//
// Environment: EDS_API_BASE (desktop only, default https://esportsdata.online), EDS_VERSION, EDS_COMMIT.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const ext = path.join(root, 'extension'), platform = path.join(root, 'web', 'platform');
const VERSION = JSON.parse(fs.readFileSync(path.join(root, 'web', 'version.json'), 'utf8')).version;

export function build({ target = 'web', outDir = path.join(root, 'dist', target), apiBase = process.env.EDS_API_BASE || 'https://esportsdata.online', version = process.env.EDS_VERSION || VERSION, commit = process.env.EDS_COMMIT || gitCommit() } = {}) {
  if (!['web', 'tauri'].includes(target)) throw new Error('target must be web or tauri');
  if (target === 'tauri' && !/^https:\/\/[a-z0-9.-]+$/i.test(apiBase)) throw new Error(`desktop API base must be an https origin, got ${apiBase}`);
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  // 1. Shared UI files. Extension-only files are left out: manifest, service worker entry, its server settings, tests.
  const skip = new Set(['manifest.json', 'background.js', 'server-config.js', 'test', 'README.md']);
  for (const name of fs.readdirSync(ext)) {
    if (skip.has(name) || /^CHANGELOG/i.test(name) || name.endsWith('.md')) continue;
    fs.cpSync(path.join(ext, name), path.join(outDir, name), { recursive: true });
  }
  // 2. The extension's background feed engine runs inside the page: same code, its own scope.
  const background = fs.readFileSync(path.join(ext, 'background.js'), 'utf8').split('\n');
  if (!background[0].startsWith('importScripts(')) throw new Error('background.js no longer starts with importScripts(); update web/build.mjs');
  fs.writeFileSync(path.join(outDir, 'background-web.js'), "'use strict';\n// Generated by web/build.mjs from extension/background.js: the feed engine (poll + SSE + notifications) in page scope.\n(function(){\n" + background.slice(1).join('\n') + '\n})();\n');
  // 3. Platform layer.
  for (const f of ['platform.js', 'platform.css', 'server-config.js']) fs.copyFileSync(path.join(platform, f), path.join(outDir, f));
  fs.writeFileSync(path.join(outDir, 'robots.txt'), 'User-agent: *\nDisallow: /\n');

  // 4. index.html from app.html: platform first, the app scripts are loaded by platform.js after sign-in.
  let html = fs.readFileSync(path.join(ext, 'app.html'), 'utf8');
  const scripts = [...html.matchAll(/<script src="([^"]+)"><\/script>/g)].map((m) => m[1]).filter((s) => s !== 'theme-boot.js' && s !== 'server-config.js');
  if (!scripts.includes('app.js')) throw new Error('app.html has no app.js script');
  const ordered = ['server-config.js', ...scripts.slice(0, scripts.indexOf('app.js')), 'background-web.js', 'app.js', ...scripts.slice(scripts.indexOf('app.js') + 1)];
  html = html.replace(/<script src="(?!theme-boot\.js)[^"]+"><\/script>/g, '');
  html = html.replace('<title>Esports Monitor</title>', '<title>Esports Monitor · Esports Data</title>\n<meta name="robots" content="noindex,nofollow">\n<link rel="icon" type="image/png" sizes="32x32" href="icons/icon32.png">');
  html = html.replace('<script src="theme-boot.js"></script>', '<script src="theme-boot.js"></script>\n<script src="platform-config.js"></script>\n<script src="platform.js"></script>');
  html = html.replace('<link rel="stylesheet" href="stats.css">', '<link rel="stylesheet" href="stats.css">\n<link rel="stylesheet" href="platform.css">');
  const gate = `<div id="boot" class="boot" aria-busy="true"><img class="brand-mark" src="icons/mark.svg" alt="" width="40" height="40"></div>
<div id="gate" class="gate" hidden>
 <form id="gateForm" class="gate-card" autocomplete="off" novalidate>
  <div class="gate-brand"><img class="brand-mark" src="icons/mark.svg" alt="" aria-hidden="true" width="32" height="32"><b>Esports Monitor</b></div>
  <h1>Вход по ключу доступа</h1>
  <p class="lead">Введите ключ, выданный администратором. На этом устройстве вход сохранится — вводить ключ каждый раз не нужно.</p>
  <div id="gateNotice" class="banner warn" role="alert" hidden></div>
  <label class="gate-field"><span>Ключ доступа</span><span class="gate-input"><input id="gateKey" class="input" type="password" name="access-key" autocomplete="off" autocapitalize="off" spellcheck="false" inputmode="text" aria-describedby="gateError" required><button type="button" id="gateReveal" class="btn ghost" aria-pressed="false" aria-label="Показать ключ">Показать</button></span></label>
  <button id="gateSubmit" class="btn primary" type="submit">Войти</button>
  <p id="gateError" class="gate-error" role="status" aria-live="polite"></p>
  <p class="gate-foot">Один ключ работает в одном профиле браузера или приложении. Вход этим же ключом в другом месте завершит сессию здесь. Сам ключ не сохраняется ни в браузере, ни в приложении.</p>
 </form>
</div>
`;
  if (!html.includes('<div id="app" class="app">')) throw new Error('app.html layout changed: #app not found');
  html = html.replace('<div id="app" class="app">', gate + '<div id="app" class="app" hidden>');
  fs.writeFileSync(path.join(outDir, 'index.html'), html);
  fs.rmSync(path.join(outDir, 'app.html'));

  // 5. Secondary pages (calculator, score log): platform layer before their own scripts.
  for (const page of ['odds.html', 'score-history.html']) {
    const file = path.join(outDir, page);
    const text = fs.readFileSync(file, 'utf8');
    if (!text.includes('<script src="server-config.js"></script>')) throw new Error(`${page}: server-config.js script tag not found`);
    fs.writeFileSync(file, text.replace('<script src="server-config.js"></script>', '<script src="platform-config.js"></script><script src="platform.js"></script><script src="server-config.js"></script><link rel="stylesheet" href="platform.css">'));
  }

  // 6. Cache busting: every local script/stylesheet reference carries ?v=<content hash> (served as immutable).
  const hash = (f) => createHash('sha256').update(fs.readFileSync(path.join(outDir, f))).digest('hex').slice(0, 10);
  const versioned = (f) => `${f}?v=${hash(f)}`;
  const config = { target, version, commit, protocol: 1, builtAt: new Date().toISOString(), apiBase: target === 'tauri' ? apiBase.replace(/\/+$/, '') : '', scripts: ordered.map(versioned) };
  fs.writeFileSync(path.join(outDir, 'platform-config.js'), `'use strict';\n// Generated by web/build.mjs. No secrets: build target, version and the list of app scripts.\nwindow.__EDS_BUILD__=Object.freeze(${JSON.stringify(config)});\n`);
  for (const page of ['index.html', 'odds.html', 'score-history.html']) {
    const file = path.join(outDir, page);
    const text = fs.readFileSync(file, 'utf8').replace(/(<script src=|<link rel="stylesheet" href=)"([^"?:]+\.(?:js|css))"/g, (m, lead, f) => (fs.existsSync(path.join(outDir, f)) ? `${lead}"${versioned(f)}"` : m));
    fs.writeFileSync(file, text);
  }
  const files = listFiles(outDir);
  const manifest = { ...config, files: files.length, bytes: files.reduce((n, f) => n + fs.statSync(path.join(outDir, f)).size, 0) };
  fs.writeFileSync(path.join(outDir, 'build-info.json'), JSON.stringify({ target, version, commit, builtAt: config.builtAt }) + '\n');
  return { outDir, ...manifest };
}

export function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? listFiles(path.join(dir, e.name), base) : [path.relative(base, path.join(dir, e.name))]));
}

function gitCommit() {
  try {
    const sha = execFileSync('git', ['-C', root, 'rev-parse', '--short=10', 'HEAD'], { encoding: 'utf8' }).trim();
    const dirty = execFileSync('git', ['-C', root, 'status', '--porcelain', '--', 'extension', 'web/platform', 'web/build.mjs'], { encoding: 'utf8' }).trim();
    return sha + (dirty ? '-dirty' : '');
  } catch { return 'unknown'; }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const i = process.argv.indexOf('--target'), target = i > 0 ? process.argv[i + 1] : 'web';
  const out = process.argv.includes('--out') ? path.resolve(process.argv[process.argv.indexOf('--out') + 1]) : undefined;
  const result = build({ target, ...(out ? { outDir: out } : {}) });
  console.log(`built ${target} ${result.version} (${result.commit}) → ${result.outDir}: ${result.files} files, ${(result.bytes / 1048576).toFixed(2)} MiB`);
}
